<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>ConectaProveedores</AssemblyName>
    <RootNamespace>ssConectaProveedores</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <PropertyGroup>
    <DefaultItemExcludes>bin\**;Records\**;referencesProxy\**;CustomServices\**;CustomClients\**;packages\**;CustomHandlers\**;**\*.cache</DefaultItemExcludes>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
        <ProjectReference Include="referencesProxy/ConectaProveedoresReferencesProxy.csproj">
        <Project>{F3BEB653-9E30-4E65-A8BB-3192461CBF8D}</Project>
        <Name>ConectaProveedoresReferencesProxy</Name>
        <Package>{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</Package>
    </ProjectReference>
    <ProjectReference Include="Records/ConectaProveedoresRecords.csproj">
        <Project>{2C35AFE4-FC96-4BB9-BF18-F0B958E7FB2C}</Project>
        <Name>ConectaProveedoresRecords</Name>
        <Package>{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</Package>
    </ProjectReference>
    <ProjectReference Include="CustomClients/Notifications/ConectaProveedores.Notifications.csproj">
        <Project>{35F479CC-D232-1296-2348-F11F2221EBED}</Project>
        <Name>ConectaProveedores.Notifications</Name>
        <Package>{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</Package>
    </ProjectReference>
<Reference Include="A2A">
  <HintPath>../bin/A2A.dll</HintPath>
</Reference>
<Reference Include="AWSSDK.Core">
  <HintPath>../bin/AWSSDK.Core.dll</HintPath>
</Reference>
<Reference Include="AWSSDK.S3">
  <HintPath>../bin/AWSSDK.S3.dll</HintPath>
</Reference>
<Reference Include="AWSSDK.SecurityToken">
  <HintPath>../bin/AWSSDK.SecurityToken.dll</HintPath>
</Reference>
<Reference Include="BouncyCastle.Crypto">
  <HintPath>../bin/BouncyCastle.Crypto.dll</HintPath>
</Reference>
<Reference Include="Duende.IdentityModel">
  <HintPath>../bin/Duende.IdentityModel.dll</HintPath>
</Reference>
<Reference Include="ExcelDataReader">
  <HintPath>../bin/ExcelDataReader.dll</HintPath>
</Reference>
<Reference Include="GemBox.Spreadsheet">
  <HintPath>../bin/GemBox.Spreadsheet.dll</HintPath>
</Reference>
<Reference Include="Google.Protobuf">
  <HintPath>../bin/Google.Protobuf.dll</HintPath>
</Reference>
<Reference Include="Grpc.Core.Api">
  <HintPath>../bin/Grpc.Core.Api.dll</HintPath>
</Reference>
<Reference Include="Grpc.Net.Client">
  <HintPath>../bin/Grpc.Net.Client.dll</HintPath>
</Reference>
<Reference Include="Grpc.Net.ClientFactory">
  <HintPath>../bin/Grpc.Net.ClientFactory.dll</HintPath>
</Reference>
<Reference Include="Grpc.Net.Common">
  <HintPath>../bin/Grpc.Net.Common.dll</HintPath>
</Reference>
<Reference Include="HarfBuzzSharp">
  <HintPath>../bin/HarfBuzzSharp.dll</HintPath>
</Reference>
<Reference Include="MailKitLite">
  <HintPath>../bin/MailKitLite.dll</HintPath>
</Reference>
<Reference Include="Microsoft.AspNetCore.Authentication.JwtBearer">
  <HintPath>../bin/Microsoft.AspNetCore.Authentication.JwtBearer.dll</HintPath>
</Reference>
<Reference Include="Microsoft.AspNetCore.HeaderPropagation">
  <HintPath>../bin/Microsoft.AspNetCore.HeaderPropagation.dll</HintPath>
</Reference>
<Reference Include="Microsoft.AspNetCore.Http.Connections.Client">
  <HintPath>../bin/Microsoft.AspNetCore.Http.Connections.Client.dll</HintPath>
</Reference>
<Reference Include="Microsoft.AspNetCore.JsonPatch">
  <HintPath>../bin/Microsoft.AspNetCore.JsonPatch.dll</HintPath>
</Reference>
<Reference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson">
  <HintPath>../bin/Microsoft.AspNetCore.Mvc.NewtonsoftJson.dll</HintPath>
</Reference>
<Reference Include="Microsoft.AspNetCore.SignalR.Client.Core">
  <HintPath>../bin/Microsoft.AspNetCore.SignalR.Client.Core.dll</HintPath>
</Reference>
<Reference Include="Microsoft.AspNetCore.SignalR.Client">
  <HintPath>../bin/Microsoft.AspNetCore.SignalR.Client.dll</HintPath>
</Reference>
<Reference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson">
  <HintPath>../bin/Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson.dll</HintPath>
</Reference>
<Reference Include="Microsoft.Bcl.Numerics">
  <HintPath>../bin/Microsoft.Bcl.Numerics.dll</HintPath>
</Reference>
<Reference Include="Microsoft.Extensions.AI.Abstractions">
  <HintPath>../bin/Microsoft.Extensions.AI.Abstractions.dll</HintPath>
</Reference>
<Reference Include="Microsoft.IdentityModel.Abstractions">
  <HintPath>../bin/Microsoft.IdentityModel.Abstractions.dll</HintPath>
</Reference>
<Reference Include="Microsoft.IdentityModel.JsonWebTokens">
  <HintPath>../bin/Microsoft.IdentityModel.JsonWebTokens.dll</HintPath>
</Reference>
<Reference Include="Microsoft.IdentityModel.Logging">
  <HintPath>../bin/Microsoft.IdentityModel.Logging.dll</HintPath>
</Reference>
<Reference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect">
  <HintPath>../bin/Microsoft.IdentityModel.Protocols.OpenIdConnect.dll</HintPath>
</Reference>
<Reference Include="Microsoft.IdentityModel.Protocols">
  <HintPath>../bin/Microsoft.IdentityModel.Protocols.dll</HintPath>
</Reference>
<Reference Include="Microsoft.IdentityModel.Tokens">
  <HintPath>../bin/Microsoft.IdentityModel.Tokens.dll</HintPath>
</Reference>
<Reference Include="MimeKitLite">
  <HintPath>../bin/MimeKitLite.dll</HintPath>
</Reference>
<Reference Include="NATS.Client.Abstractions">
  <HintPath>../bin/NATS.Client.Abstractions.dll</HintPath>
</Reference>
<Reference Include="NATS.Client.Core">
  <HintPath>../bin/NATS.Client.Core.dll</HintPath>
</Reference>
<Reference Include="NATS.Client.JetStream">
  <HintPath>../bin/NATS.Client.JetStream.dll</HintPath>
</Reference>
<Reference Include="NATS.Client.Serializers.Json">
  <HintPath>../bin/NATS.Client.Serializers.Json.dll</HintPath>
</Reference>
<Reference Include="NATS.NKeys">
  <HintPath>../bin/NATS.NKeys.dll</HintPath>
</Reference>
<Reference Include="Newtonsoft.Json.Bson">
  <HintPath>../bin/Newtonsoft.Json.Bson.dll</HintPath>
</Reference>
<Reference Include="Newtonsoft.Json">
  <HintPath>../bin/Newtonsoft.Json.dll</HintPath>
</Reference>
<Reference Include="Npgsql">
  <HintPath>../bin/Npgsql.dll</HintPath>
</Reference>
<Reference Include="OpenTelemetry.Api.ProviderBuilderExtensions">
  <HintPath>../bin/OpenTelemetry.Api.ProviderBuilderExtensions.dll</HintPath>
</Reference>
<Reference Include="OpenTelemetry.Api">
  <HintPath>../bin/OpenTelemetry.Api.dll</HintPath>
</Reference>
<Reference Include="OpenTelemetry.Exporter.Console">
  <HintPath>../bin/OpenTelemetry.Exporter.Console.dll</HintPath>
</Reference>
<Reference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol">
  <HintPath>../bin/OpenTelemetry.Exporter.OpenTelemetryProtocol.dll</HintPath>
</Reference>
<Reference Include="OpenTelemetry.Extensions.Hosting">
  <HintPath>../bin/OpenTelemetry.Extensions.Hosting.dll</HintPath>
</Reference>
<Reference Include="OpenTelemetry.Instrumentation.AspNetCore">
  <HintPath>../bin/OpenTelemetry.Instrumentation.AspNetCore.dll</HintPath>
</Reference>
<Reference Include="OpenTelemetry.Instrumentation.Http">
  <HintPath>../bin/OpenTelemetry.Instrumentation.Http.dll</HintPath>
</Reference>
<Reference Include="OpenTelemetry">
  <HintPath>../bin/OpenTelemetry.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Abstractions">
  <HintPath>../bin/OutSystems.Application.Abstractions.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.AgentEval">
  <HintPath>../bin/OutSystems.Application.AgentEval.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Analytics">
  <HintPath>../bin/OutSystems.Application.Analytics.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.AppHealth">
  <HintPath>../bin/OutSystems.Application.AppHealth.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Caching">
  <HintPath>../bin/OutSystems.Application.Caching.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Core">
  <HintPath>../bin/OutSystems.Application.Core.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.DataPreview">
  <HintPath>../bin/OutSystems.Application.DataPreview.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Debugging">
  <HintPath>../bin/OutSystems.Application.Debugging.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Diagnostics">
  <HintPath>../bin/OutSystems.Application.Diagnostics.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Emails">
  <HintPath>../bin/OutSystems.Application.Emails.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.ErrorHandling">
  <HintPath>../bin/OutSystems.Application.ErrorHandling.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Events">
  <HintPath>../bin/OutSystems.Application.Events.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Extensibility.Implementation">
  <HintPath>../bin/OutSystems.Application.Extensibility.Implementation.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Extensibility">
  <HintPath>../bin/OutSystems.Application.Extensibility.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.ExternalAgents">
  <HintPath>../bin/OutSystems.Application.ExternalAgents.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.ExternalLibraries">
  <HintPath>../bin/OutSystems.Application.ExternalLibraries.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.ExternalSearches">
  <HintPath>../bin/OutSystems.Application.ExternalSearches.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Files">
  <HintPath>../bin/OutSystems.Application.Files.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.GlobalEvents">
  <HintPath>../bin/OutSystems.Application.GlobalEvents.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Identity">
  <HintPath>../bin/OutSystems.Application.Identity.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Initialization.ASPNetCore">
  <HintPath>../bin/OutSystems.Application.Initialization.ASPNetCore.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Logic">
  <HintPath>../bin/OutSystems.Application.Logic.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.ManifestGeneration">
  <HintPath>../bin/OutSystems.Application.ManifestGeneration.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Models">
  <HintPath>../bin/OutSystems.Application.Models.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.ProducerCapabilities">
  <HintPath>../bin/OutSystems.Application.ProducerCapabilities.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Public">
  <HintPath>../bin/OutSystems.Application.Public.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Reasoning">
  <HintPath>../bin/OutSystems.Application.Reasoning.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.RestConsume">
  <HintPath>../bin/OutSystems.Application.RestConsume.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.S3Client">
  <HintPath>../bin/OutSystems.Application.S3Client.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Security">
  <HintPath>../bin/OutSystems.Application.Security.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.SemanticSearch">
  <HintPath>../bin/OutSystems.Application.SemanticSearch.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Session">
  <HintPath>../bin/OutSystems.Application.Session.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.SignerClient">
  <HintPath>../bin/OutSystems.Application.SignerClient.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Spreadsheets">
  <HintPath>../bin/OutSystems.Application.Spreadsheets.dll</HintPath>
</Reference>
<Reference Include="Pgvector">
  <HintPath>../bin/Pgvector.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Timers">
  <HintPath>../bin/OutSystems.Application.Timers.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Transports">
  <HintPath>../bin/OutSystems.Application.Transports.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Application.Workflows">
  <HintPath>../bin/OutSystems.Application.Workflows.dll</HintPath>
</Reference>
<Reference Include="OutSystems.CachingCommon">
  <HintPath>../bin/OutSystems.CachingCommon.dll</HintPath>
</Reference>
<Reference Include="OutSystems.DatabaseProvider.QueryEngine.Driver">
  <HintPath>../bin/OutSystems.DatabaseProvider.QueryEngine.Driver.dll</HintPath>
</Reference>
<Reference Include="OutSystems.DebuggerClient">
  <HintPath>../bin/OutSystems.DebuggerClient.dll</HintPath>
</Reference>
<Reference Include="OutSystems.HubEdition.DatabaseAbstractionLayer">
  <HintPath>../bin/OutSystems.HubEdition.DatabaseAbstractionLayer.dll</HintPath>
</Reference>
<Reference Include="OutSystems.HubEdition.PostgreSQLDatabaseProvider">
  <HintPath>../bin/OutSystems.HubEdition.PostgreSQLDatabaseProvider.dll</HintPath>
</Reference>
<Reference Include="OutSystems.HubEdition.QueryEngineDatabaseProvider">
  <HintPath>../bin/OutSystems.HubEdition.QueryEngineDatabaseProvider.dll</HintPath>
</Reference>
<Reference Include="OutSystems.HubEdition.RuntimePlatform">
  <HintPath>../bin/OutSystems.HubEdition.RuntimePlatform.dll</HintPath>
</Reference>
<Reference Include="OutSystems.OpenTelemetry">
  <HintPath>../bin/OutSystems.OpenTelemetry.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Plugin.Caching.Nats">
  <HintPath>../bin/OutSystems.Plugin.Caching.Nats.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Plugin.Caching.NoInvalidation">
  <HintPath>../bin/OutSystems.Plugin.Caching.NoInvalidation.dll</HintPath>
</Reference>
<Reference Include="OutSystems.PluginAPI">
  <HintPath>../bin/OutSystems.PluginAPI.dll</HintPath>
</Reference>
<Reference Include="OutSystems.RESTService.Runtime.Abstractions">
  <HintPath>../bin/OutSystems.RESTService.Runtime.Abstractions.dll</HintPath>
</Reference>
<Reference Include="OutSystems.RESTService.Runtime.Core">
  <HintPath>../bin/OutSystems.RESTService.Runtime.Core.dll</HintPath>
</Reference>
<Reference Include="OutSystems.RuntimeCommon">
  <HintPath>../bin/OutSystems.RuntimeCommon.dll</HintPath>
</Reference>
<Reference Include="OutSystems.RuntimeSettingsConfiguration">
  <HintPath>../bin/OutSystems.RuntimeSettingsConfiguration.dll</HintPath>
</Reference>
<Reference Include="OutSystems.Spreadsheet">
  <HintPath>../bin/OutSystems.Spreadsheet.dll</HintPath>
</Reference>
<Reference Include="Polly.Core">
  <HintPath>../bin/Polly.Core.dll</HintPath>
</Reference>
<Reference Include="Polly.RateLimiting">
  <HintPath>../bin/Polly.RateLimiting.dll</HintPath>
</Reference>
<Reference Include="Prometheus.AspNetCore">
  <HintPath>../bin/Prometheus.AspNetCore.dll</HintPath>
</Reference>
<Reference Include="Prometheus.NetCore">
  <HintPath>../bin/Prometheus.NetCore.dll</HintPath>
</Reference>
<Reference Include="Prometheus.NetStandard">
  <HintPath>../bin/Prometheus.NetStandard.dll</HintPath>
</Reference>
<Reference Include="SkiaSharp">
  <HintPath>../bin/SkiaSharp.dll</HintPath>
</Reference>
<Reference Include="SpreadCheetah">
  <HintPath>../bin/SpreadCheetah.dll</HintPath>
</Reference>
<Reference Include="Stubble.Core">
  <HintPath>../bin/Stubble.Core.dll</HintPath>
</Reference>
<Reference Include="System.Data.CData.ApachePhoenix">
  <HintPath>../bin/System.Data.CData.ApachePhoenix.dll</HintPath>
</Reference>
<Reference Include="System.IdentityModel.Tokens.Jwt">
  <HintPath>../bin/System.IdentityModel.Tokens.Jwt.dll</HintPath>
</Reference>
<Reference Include="prometheus-net.DotNetRuntime">
  <HintPath>../bin/prometheus-net.DotNetRuntime.dll</HintPath>
</Reference>

  </ItemGroup>

  <ItemGroup>
    <Content Update="appSettings.config;appsettings.json;basesettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="*.manifest">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
            <EmbeddedResource Include="b_CyA_Emails.TreasuryReminder.html.resources" />
        <EmbeddedResource Include="b_CyA_Emails.LoginAlert.html.resources" />
        <EmbeddedResource Include="a_Emails.ChangeEmail.html.resources" />
        <EmbeddedResource Include="a_Emails.Supplier2FA.html.resources" />
        <EmbeddedResource Include="e_Orders_Emails.RejectOrderReqFile.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.AccountingError.html.resources" />
        <EmbeddedResource Include="d_Inv_Emails.MissingInvoiceProveedor.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.ReassignmentFolioNotifyTargetUser.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.FailedEntry.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.PreApprovalCanceledFolio.html.resources" />
        <EmbeddedResource Include="c_Req_Emails.ModifyRequisition.html.resources" />
        <EmbeddedResource Include="d_Inv_Emails.ModifyAccountingInvoice.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.FolioInvoiceRejected.html.resources" />
        <EmbeddedResource Include="c_Req_Emails.NextApproverRequisition.html.resources" />
        <EmbeddedResource Include="e_Orders_Emails.ApprovalRejectOrder.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.FolioIncorrectAssignment.html.resources" />
        <EmbeddedResource Include="d_Inv_Emails.NextApproverInvoice.html.resources" />
        <EmbeddedResource Include="b_CyA_Emails.CanceledProposal.html.resources" />
        <EmbeddedResource Include="e_Orders_Emails.FirstApproverOrderFile.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.FolioApproved.html.resources" />
        <EmbeddedResource Include="d_Inv_Emails.CanceledInvoice.html.resources" />
        <EmbeddedResource Include="d_Inv_Emails.ModifyInvoice.html.resources" />
        <EmbeddedResource Include="d_Inv_Emails.FirstApproverInvoice.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.NextApproverFolio.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.EvidenceReviewFolio.html.resources" />
        <EmbeddedResource Include="c_Req_Emails.ApprovedRequisition.html.resources" />
        <EmbeddedResource Include="h_OrderDistribution_Emails.InvoiceErrorNotification.html.resources" />
        <EmbeddedResource Include="b_CyA_Emails.ProposalLinesReminder.html.resources" />
        <EmbeddedResource Include="c_Req_Emails.FirstApproverRequisition.html.resources" />
        <EmbeddedResource Include="ConectaProveedoresLanguage.es-MX.resources" />
        <EmbeddedResource Include="e_Orders_Emails.NextApproverOrder.html.resources" />
        <EmbeddedResource Include="d_Inv_Emails.InvoiceAccountingFailed.html.resources" />
        <EmbeddedResource Include="e_Orders_Emails.NextApproverOrderFile.html.resources" />
        <EmbeddedResource Include="b_CyA_Emails.ErrorAPI.html.resources" />
        <EmbeddedResource Include="h_OrderDistribution_Emails.RejectOrderDistribution.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.ReassignRejectedFolios.html.resources" />
        <EmbeddedResource Include="e_Orders_Emails.OrderRequestedFiles.html.resources" />
        <EmbeddedResource Include="e_Orders_Emails.OrderApproved.html.resources" />
        <EmbeddedResource Include="a_Emails.RequestDocuments.html.resources" />
        <EmbeddedResource Include="d_Inv_Emails.AmortizationInvoice.html.resources" />
        <EmbeddedResource Include="h_OrderDistribution_Emails.OrderDestributionNotification.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.FirstApproverFolio.html.resources" />
        <EmbeddedResource Include="a_Emails.GlobalActivityEmailNotification.html.resources" />
        <EmbeddedResource Include="d_Inv_Emails.InvoiceApproved.html.resources" />
        <EmbeddedResource Include="a_Emails.ReassignmentNotifyTargetUser.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.AccountingOrderError.html.resources" />
        <EmbeddedResource Include="ConectaProveedoresLanguage.resources" />
        <EmbeddedResource Include="h_OrderDistribution_Emails.OrderChangeNotification.html.resources" />
        <EmbeddedResource Include="ConectaProveedoresLanguage.en-US.resources" />
        <EmbeddedResource Include="e_Orders_Emails.FirstApproverOrder.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.CanceledFolio.html.resources" />
        <EmbeddedResource Include="c_Req_Emails.CanceledRequisition.html.resources" />
        <EmbeddedResource Include="b_CyA_Emails.RejectedProposal.html.resources" />
        <EmbeddedResource Include="a_Emails.ResetPassword.html.resources" />
        <EmbeddedResource Include="b_CyA_Emails.ProposalStatusChange.html.resources" />
        <EmbeddedResource Include="e_Orders_Emails.RejectOrder.html.resources" />
        <EmbeddedResource Include="j_FoliosSAE_Emails.EvidenceRequestFolio.html.resources" />

  </ItemGroup>

</Project>
