using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("InvoiceMainFiles")]
public RestList<ssConectaProveedores.RestRecords.RESTST_d381fba44897ce4382b17d5149465d51Structure> outParamInvoiceMainFiles;


    public static RESTConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Outputs FromOutputs(IBehaviorsConfiguration conf, RL_cc11123f1ba1bfd417e2f33be28138e9 outParamInvoiceMainFiles) {RESTConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Outputs result = new RESTConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Outputs();
// Write optimized result.outParamInvoiceMainFiles
result.outParamInvoiceMainFiles = new RL_cc11123f1ba1bfd417e2f33be28138e9().ToRestList<ssConectaProveedores.RestRecords.RESTST_d381fba44897ce4382b17d5149465d51Structure>(ssConectaProveedores.RestRecords.RESTST_d381fba44897ce4382b17d5149465d51Structure.FromStructureDelegate(conf));
return result;
}


    public static ConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Model ToModel(RESTConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Outputs variables) {ConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Model result = new ConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Model();
result.outParamInvoiceMainFiles = variables == null ? new RL_cc11123f1ba1bfd417e2f33be28138e9() : RL_cc11123f1ba1bfd417e2f33be28138e9.FromRestList(variables.outParamInvoiceMainFiles, ssConectaProveedores.RestRecords.RESTST_d381fba44897ce4382b17d5149465d51Structure.ToStructure);
return result;
}


    public static RESTConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Outputs result = new RESTConectaProveedores_j_FoliosSAE_Wb_FolioEditIncorrectInvoice_DataActionGetFolioFiles_Outputs();
result.outParamInvoiceMainFiles = screenModel.outParamInvoiceMainFiles.ToRestList<ssConectaProveedores.RestRecords.RESTST_d381fba44897ce4382b17d5149465d51Structure>(ssConectaProveedores.RestRecords.RESTST_d381fba44897ce4382b17d5149465d51Structure.FromStructureDelegate(conf));
return result;
}

}
