using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_ContractFile")]
public ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_ContractFile;
[JsonProperty("o_AttachFilesList")]
public RestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure> outParamo_AttachFilesList;
[JsonProperty("o_ContractDepositList")]
public RestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure> outParamo_ContractDepositList;
[JsonProperty("o_ContractInsuranceList")]
public RestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure> outParamo_ContractInsuranceList;
[JsonProperty("o_ContractAdvancePayment")]
public ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_ContractAdvancePayment;
[JsonProperty("o_ContractPendingJustification")]
public ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_ContractPendingJustification;


    public static RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Outputs FromOutputs(IBehaviorsConfiguration conf, ST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_ContractFile, RL_7a479a555821b093171c5d3cd3382006 outParamo_AttachFilesList, RL_7a479a555821b093171c5d3cd3382006 outParamo_ContractDepositList, RL_7a479a555821b093171c5d3cd3382006 outParamo_ContractInsuranceList, ST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_ContractAdvancePayment, ST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_ContractPendingJustification) {RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Outputs result = new RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Outputs();
// Write the needed fields of the record outParamo_ContractFile to the result.outParamo_ContractFile
result.outParamo_ContractFile = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_ContractFile.ssRequisitionContractFile to the result.outParamo_ContractFile.AttrRequisitionContractFile
result.outParamo_ContractFile.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
result.outParamo_ContractFile.AttrRequisitionContractFile.AttrId = (long?) outParamo_ContractFile.ssRequisitionContractFile.ssId;
result.outParamo_ContractFile.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_ContractFile.ssRequisitionContractFile.ssRequisitionId;
result.outParamo_ContractFile.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_ContractFile.ssRequisitionContractFile.ssRequisitionFileId;
result.outParamo_ContractFile.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_ContractFile.ssRequisitionContractFile.ssContractFileTypeId;
result.outParamo_ContractFile.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_ContractFile.ssRequisitionContractFile.ssAmount;
result.outParamo_ContractFile.AttrRequisitionContractFile.AttrCurrencyId = outParamo_ContractFile.ssRequisitionContractFile.ssCurrencyId;
result.outParamo_ContractFile.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_ContractFile.ssRequisitionContractFile.ssDepositTypeId;
result.outParamo_ContractFile.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractFile.ssRequisitionContractFile.ssInsuranceTypeId;
result.outParamo_ContractFile.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractFile.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_ContractFile.ssRequisitionFile to the result.outParamo_ContractFile.AttrRequisitionFile
result.outParamo_ContractFile.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
result.outParamo_ContractFile.AttrRequisitionFile.AttrId = (long?) outParamo_ContractFile.ssRequisitionFile.ssId;
result.outParamo_ContractFile.AttrRequisitionFile.AttrFilename = outParamo_ContractFile.ssRequisitionFile.ssFilename;
result.outParamo_ContractFile.AttrRequisitionFile.AttrVENDOR = outParamo_ContractFile.ssRequisitionFile.ssVENDOR;
result.outParamo_ContractFile.AttrRequisitionFile.AttrDOC_TYPE = outParamo_ContractFile.ssRequisitionFile.ssDOC_TYPE;
result.outParamo_ContractFile.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_ContractFile.ssRequisitionFile.ssSAP_OBJECT;
result.outParamo_ContractFile.AttrRequisitionFile.AttrCreatedBy = outParamo_ContractFile.ssRequisitionFile.ssCreatedBy;
result.outParamo_ContractFile.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractFile.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_ContractFile.AttrRequisitionFile.AttrStorageId = (long?) outParamo_ContractFile.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractFile.ssValid to the result.outParamo_ContractFile.AttrValid
result.outParamo_ContractFile.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_ContractFile.AttrValid.AttrIsValid = (bool?) outParamo_ContractFile.ssValid.ssIsValid;
result.outParamo_ContractFile.AttrValid.AttrValidationMessage = outParamo_ContractFile.ssValid.ssValidationMessage;
result.outParamo_ContractFile.AttrBinary = outParamo_ContractFile.ssBinary;
result.outParamo_ContractFile.AttrBigUploadfileId = (long?) outParamo_ContractFile.ssBigUploadfileId;
// Write the needed fields of the list outParamo_AttachFilesList to the result.outParamo_AttachFilesList
ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure tmpoutParamo_AttachFilesListElement;
if(outParamo_AttachFilesList.Empty) {
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec to the tmpoutParamo_AttachFilesListElement
tmpoutParamo_AttachFilesListElement = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile to the tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssRequisitionId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssRequisitionFileId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssContractFileTypeId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssAmount;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrCurrencyId = outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssCurrencyId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssDepositTypeId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssInsuranceTypeId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssRequisitionFile to the tmpoutParamo_AttachFilesListElement.AttrRequisitionFile
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrFilename = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssFilename;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrVENDOR = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssVENDOR;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrDOC_TYPE = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssDOC_TYPE;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssSAP_OBJECT;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrCreatedBy = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssCreatedBy;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrStorageId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssValid to the tmpoutParamo_AttachFilesListElement.AttrValid
tmpoutParamo_AttachFilesListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_AttachFilesListElement.AttrValid.AttrIsValid = (bool?) outParamo_AttachFilesList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_AttachFilesListElement.AttrValid.AttrValidationMessage = outParamo_AttachFilesList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_AttachFilesListElement.AttrBinary = outParamo_AttachFilesList.CurrentRec.ssBinary;
tmpoutParamo_AttachFilesListElement.AttrBigUploadfileId = (long?) outParamo_AttachFilesList.CurrentRec.ssBigUploadfileId;
result.outParamo_AttachFilesList = new RestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>(new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure[] {}, tmpoutParamo_AttachFilesListElement);
} else {
List<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>
 tmpoutParamo_AttachFilesList1List = new List<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>
();
try {outParamo_AttachFilesList.StartIteration();
while (!(outParamo_AttachFilesList.Eof)) {
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec to the tmpoutParamo_AttachFilesListElement
tmpoutParamo_AttachFilesListElement = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile to the tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssRequisitionId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssRequisitionFileId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssContractFileTypeId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssAmount;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrCurrencyId = outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssCurrencyId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssDepositTypeId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssInsuranceTypeId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssRequisitionFile to the tmpoutParamo_AttachFilesListElement.AttrRequisitionFile
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssId;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrFilename = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssFilename;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrVENDOR = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssVENDOR;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrDOC_TYPE = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssDOC_TYPE;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssSAP_OBJECT;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrCreatedBy = outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssCreatedBy;
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_AttachFilesListElement.AttrRequisitionFile.AttrStorageId = (long?) outParamo_AttachFilesList.CurrentRec.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssValid to the tmpoutParamo_AttachFilesListElement.AttrValid
tmpoutParamo_AttachFilesListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_AttachFilesListElement.AttrValid.AttrIsValid = (bool?) outParamo_AttachFilesList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_AttachFilesListElement.AttrValid.AttrValidationMessage = outParamo_AttachFilesList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_AttachFilesListElement.AttrBinary = outParamo_AttachFilesList.CurrentRec.ssBinary;
tmpoutParamo_AttachFilesListElement.AttrBigUploadfileId = (long?) outParamo_AttachFilesList.CurrentRec.ssBigUploadfileId;
tmpoutParamo_AttachFilesList1List.Add(tmpoutParamo_AttachFilesListElement);
outParamo_AttachFilesList.Advance();
}

} finally {
outParamo_AttachFilesList.EndIteration();
}

result.outParamo_AttachFilesList = new RestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>(tmpoutParamo_AttachFilesList1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure));
}

// Write the needed fields of the list outParamo_ContractDepositList to the result.outParamo_ContractDepositList
ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure tmpoutParamo_ContractDepositListElement;
if(outParamo_ContractDepositList.Empty) {
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec to the tmpoutParamo_ContractDepositListElement
tmpoutParamo_ContractDepositListElement = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile to the tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssRequisitionId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssRequisitionFileId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssContractFileTypeId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssAmount;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrCurrencyId = outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssCurrencyId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssDepositTypeId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssInsuranceTypeId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssRequisitionFile to the tmpoutParamo_ContractDepositListElement.AttrRequisitionFile
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrFilename = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssFilename;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrVENDOR = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssVENDOR;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrDOC_TYPE = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssDOC_TYPE;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssSAP_OBJECT;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrCreatedBy = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssCreatedBy;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrStorageId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssValid to the tmpoutParamo_ContractDepositListElement.AttrValid
tmpoutParamo_ContractDepositListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_ContractDepositListElement.AttrValid.AttrIsValid = (bool?) outParamo_ContractDepositList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_ContractDepositListElement.AttrValid.AttrValidationMessage = outParamo_ContractDepositList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_ContractDepositListElement.AttrBinary = outParamo_ContractDepositList.CurrentRec.ssBinary;
tmpoutParamo_ContractDepositListElement.AttrBigUploadfileId = (long?) outParamo_ContractDepositList.CurrentRec.ssBigUploadfileId;
result.outParamo_ContractDepositList = new RestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>(new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure[] {}, tmpoutParamo_ContractDepositListElement);
} else {
List<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>
 tmpoutParamo_ContractDepositList1List = new List<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>
();
try {outParamo_ContractDepositList.StartIteration();
while (!(outParamo_ContractDepositList.Eof)) {
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec to the tmpoutParamo_ContractDepositListElement
tmpoutParamo_ContractDepositListElement = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile to the tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssRequisitionId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssRequisitionFileId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssContractFileTypeId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssAmount;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrCurrencyId = outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssCurrencyId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssDepositTypeId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssInsuranceTypeId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssRequisitionFile to the tmpoutParamo_ContractDepositListElement.AttrRequisitionFile
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssId;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrFilename = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssFilename;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrVENDOR = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssVENDOR;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrDOC_TYPE = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssDOC_TYPE;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssSAP_OBJECT;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrCreatedBy = outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssCreatedBy;
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_ContractDepositListElement.AttrRequisitionFile.AttrStorageId = (long?) outParamo_ContractDepositList.CurrentRec.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssValid to the tmpoutParamo_ContractDepositListElement.AttrValid
tmpoutParamo_ContractDepositListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_ContractDepositListElement.AttrValid.AttrIsValid = (bool?) outParamo_ContractDepositList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_ContractDepositListElement.AttrValid.AttrValidationMessage = outParamo_ContractDepositList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_ContractDepositListElement.AttrBinary = outParamo_ContractDepositList.CurrentRec.ssBinary;
tmpoutParamo_ContractDepositListElement.AttrBigUploadfileId = (long?) outParamo_ContractDepositList.CurrentRec.ssBigUploadfileId;
tmpoutParamo_ContractDepositList1List.Add(tmpoutParamo_ContractDepositListElement);
outParamo_ContractDepositList.Advance();
}

} finally {
outParamo_ContractDepositList.EndIteration();
}

result.outParamo_ContractDepositList = new RestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>(tmpoutParamo_ContractDepositList1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure));
}

// Write the needed fields of the list outParamo_ContractInsuranceList to the result.outParamo_ContractInsuranceList
ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure tmpoutParamo_ContractInsuranceListElement;
if(outParamo_ContractInsuranceList.Empty) {
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec to the tmpoutParamo_ContractInsuranceListElement
tmpoutParamo_ContractInsuranceListElement = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile to the tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssRequisitionId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssRequisitionFileId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssContractFileTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssAmount;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrCurrencyId = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssCurrencyId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssDepositTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssInsuranceTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile to the tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrFilename = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssFilename;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrVENDOR = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssVENDOR;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrDOC_TYPE = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssDOC_TYPE;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssSAP_OBJECT;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrCreatedBy = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssCreatedBy;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrStorageId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssValid to the tmpoutParamo_ContractInsuranceListElement.AttrValid
tmpoutParamo_ContractInsuranceListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_ContractInsuranceListElement.AttrValid.AttrIsValid = (bool?) outParamo_ContractInsuranceList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_ContractInsuranceListElement.AttrValid.AttrValidationMessage = outParamo_ContractInsuranceList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_ContractInsuranceListElement.AttrBinary = outParamo_ContractInsuranceList.CurrentRec.ssBinary;
tmpoutParamo_ContractInsuranceListElement.AttrBigUploadfileId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssBigUploadfileId;
result.outParamo_ContractInsuranceList = new RestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>(new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure[] {}, tmpoutParamo_ContractInsuranceListElement);
} else {
List<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>
 tmpoutParamo_ContractInsuranceList1List = new List<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>
();
try {outParamo_ContractInsuranceList.StartIteration();
while (!(outParamo_ContractInsuranceList.Eof)) {
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec to the tmpoutParamo_ContractInsuranceListElement
tmpoutParamo_ContractInsuranceListElement = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile to the tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssRequisitionId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssRequisitionFileId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssContractFileTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssAmount;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrCurrencyId = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssCurrencyId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssDepositTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssInsuranceTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile to the tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssId;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrFilename = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssFilename;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrVENDOR = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssVENDOR;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrDOC_TYPE = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssDOC_TYPE;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssSAP_OBJECT;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrCreatedBy = outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssCreatedBy;
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_ContractInsuranceListElement.AttrRequisitionFile.AttrStorageId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssValid to the tmpoutParamo_ContractInsuranceListElement.AttrValid
tmpoutParamo_ContractInsuranceListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_ContractInsuranceListElement.AttrValid.AttrIsValid = (bool?) outParamo_ContractInsuranceList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_ContractInsuranceListElement.AttrValid.AttrValidationMessage = outParamo_ContractInsuranceList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_ContractInsuranceListElement.AttrBinary = outParamo_ContractInsuranceList.CurrentRec.ssBinary;
tmpoutParamo_ContractInsuranceListElement.AttrBigUploadfileId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssBigUploadfileId;
tmpoutParamo_ContractInsuranceList1List.Add(tmpoutParamo_ContractInsuranceListElement);
outParamo_ContractInsuranceList.Advance();
}

} finally {
outParamo_ContractInsuranceList.EndIteration();
}

result.outParamo_ContractInsuranceList = new RestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>(tmpoutParamo_ContractInsuranceList1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure));
}

// Write the needed fields of the record outParamo_ContractAdvancePayment to the result.outParamo_ContractAdvancePayment
result.outParamo_ContractAdvancePayment = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_ContractAdvancePayment.ssRequisitionContractFile to the result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile.AttrId = (long?) outParamo_ContractAdvancePayment.ssRequisitionContractFile.ssId;
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_ContractAdvancePayment.ssRequisitionContractFile.ssRequisitionId;
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_ContractAdvancePayment.ssRequisitionContractFile.ssRequisitionFileId;
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_ContractAdvancePayment.ssRequisitionContractFile.ssContractFileTypeId;
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_ContractAdvancePayment.ssRequisitionContractFile.ssAmount;
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile.AttrCurrencyId = outParamo_ContractAdvancePayment.ssRequisitionContractFile.ssCurrencyId;
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_ContractAdvancePayment.ssRequisitionContractFile.ssDepositTypeId;
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractAdvancePayment.ssRequisitionContractFile.ssInsuranceTypeId;
result.outParamo_ContractAdvancePayment.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractAdvancePayment.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_ContractAdvancePayment.ssRequisitionFile to the result.outParamo_ContractAdvancePayment.AttrRequisitionFile
result.outParamo_ContractAdvancePayment.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
result.outParamo_ContractAdvancePayment.AttrRequisitionFile.AttrId = (long?) outParamo_ContractAdvancePayment.ssRequisitionFile.ssId;
result.outParamo_ContractAdvancePayment.AttrRequisitionFile.AttrFilename = outParamo_ContractAdvancePayment.ssRequisitionFile.ssFilename;
result.outParamo_ContractAdvancePayment.AttrRequisitionFile.AttrVENDOR = outParamo_ContractAdvancePayment.ssRequisitionFile.ssVENDOR;
result.outParamo_ContractAdvancePayment.AttrRequisitionFile.AttrDOC_TYPE = outParamo_ContractAdvancePayment.ssRequisitionFile.ssDOC_TYPE;
result.outParamo_ContractAdvancePayment.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_ContractAdvancePayment.ssRequisitionFile.ssSAP_OBJECT;
result.outParamo_ContractAdvancePayment.AttrRequisitionFile.AttrCreatedBy = outParamo_ContractAdvancePayment.ssRequisitionFile.ssCreatedBy;
result.outParamo_ContractAdvancePayment.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractAdvancePayment.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_ContractAdvancePayment.AttrRequisitionFile.AttrStorageId = (long?) outParamo_ContractAdvancePayment.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractAdvancePayment.ssValid to the result.outParamo_ContractAdvancePayment.AttrValid
result.outParamo_ContractAdvancePayment.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_ContractAdvancePayment.AttrValid.AttrIsValid = (bool?) outParamo_ContractAdvancePayment.ssValid.ssIsValid;
result.outParamo_ContractAdvancePayment.AttrValid.AttrValidationMessage = outParamo_ContractAdvancePayment.ssValid.ssValidationMessage;
result.outParamo_ContractAdvancePayment.AttrBinary = outParamo_ContractAdvancePayment.ssBinary;
result.outParamo_ContractAdvancePayment.AttrBigUploadfileId = (long?) outParamo_ContractAdvancePayment.ssBigUploadfileId;
// Write the needed fields of the record outParamo_ContractPendingJustification to the result.outParamo_ContractPendingJustification
result.outParamo_ContractPendingJustification = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_ContractPendingJustification.ssRequisitionContractFile to the result.outParamo_ContractPendingJustification.AttrRequisitionContractFile
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile.AttrId = (long?) outParamo_ContractPendingJustification.ssRequisitionContractFile.ssId;
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_ContractPendingJustification.ssRequisitionContractFile.ssRequisitionId;
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_ContractPendingJustification.ssRequisitionContractFile.ssRequisitionFileId;
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_ContractPendingJustification.ssRequisitionContractFile.ssContractFileTypeId;
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_ContractPendingJustification.ssRequisitionContractFile.ssAmount;
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile.AttrCurrencyId = outParamo_ContractPendingJustification.ssRequisitionContractFile.ssCurrencyId;
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_ContractPendingJustification.ssRequisitionContractFile.ssDepositTypeId;
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractPendingJustification.ssRequisitionContractFile.ssInsuranceTypeId;
result.outParamo_ContractPendingJustification.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractPendingJustification.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_ContractPendingJustification.ssRequisitionFile to the result.outParamo_ContractPendingJustification.AttrRequisitionFile
result.outParamo_ContractPendingJustification.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
result.outParamo_ContractPendingJustification.AttrRequisitionFile.AttrId = (long?) outParamo_ContractPendingJustification.ssRequisitionFile.ssId;
result.outParamo_ContractPendingJustification.AttrRequisitionFile.AttrFilename = outParamo_ContractPendingJustification.ssRequisitionFile.ssFilename;
result.outParamo_ContractPendingJustification.AttrRequisitionFile.AttrVENDOR = outParamo_ContractPendingJustification.ssRequisitionFile.ssVENDOR;
result.outParamo_ContractPendingJustification.AttrRequisitionFile.AttrDOC_TYPE = outParamo_ContractPendingJustification.ssRequisitionFile.ssDOC_TYPE;
result.outParamo_ContractPendingJustification.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_ContractPendingJustification.ssRequisitionFile.ssSAP_OBJECT;
result.outParamo_ContractPendingJustification.AttrRequisitionFile.AttrCreatedBy = outParamo_ContractPendingJustification.ssRequisitionFile.ssCreatedBy;
result.outParamo_ContractPendingJustification.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractPendingJustification.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_ContractPendingJustification.AttrRequisitionFile.AttrStorageId = (long?) outParamo_ContractPendingJustification.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractPendingJustification.ssValid to the result.outParamo_ContractPendingJustification.AttrValid
result.outParamo_ContractPendingJustification.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_ContractPendingJustification.AttrValid.AttrIsValid = (bool?) outParamo_ContractPendingJustification.ssValid.ssIsValid;
result.outParamo_ContractPendingJustification.AttrValid.AttrValidationMessage = outParamo_ContractPendingJustification.ssValid.ssValidationMessage;
result.outParamo_ContractPendingJustification.AttrBinary = outParamo_ContractPendingJustification.ssBinary;
result.outParamo_ContractPendingJustification.AttrBigUploadfileId = (long?) outParamo_ContractPendingJustification.ssBigUploadfileId;
return result;
}


    public static ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Model ToModel(RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Outputs variables) {ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Model result = new ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Model();
result.outParamo_ContractFile = variables == null ? new ST_26b16bea631cbd94cf555acb5c7a4be3Structure() : ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.ToStructure(variables.outParamo_ContractFile);
result.outParamo_AttachFilesList = variables == null ? new RL_7a479a555821b093171c5d3cd3382006() : RL_7a479a555821b093171c5d3cd3382006.FromRestList(variables.outParamo_AttachFilesList, ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.ToStructure);
result.outParamo_ContractDepositList = variables == null ? new RL_7a479a555821b093171c5d3cd3382006() : RL_7a479a555821b093171c5d3cd3382006.FromRestList(variables.outParamo_ContractDepositList, ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.ToStructure);
result.outParamo_ContractInsuranceList = variables == null ? new RL_7a479a555821b093171c5d3cd3382006() : RL_7a479a555821b093171c5d3cd3382006.FromRestList(variables.outParamo_ContractInsuranceList, ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.ToStructure);
result.outParamo_ContractAdvancePayment = variables == null ? new ST_26b16bea631cbd94cf555acb5c7a4be3Structure() : ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.ToStructure(variables.outParamo_ContractAdvancePayment);
result.outParamo_ContractPendingJustification = variables == null ? new ST_26b16bea631cbd94cf555acb5c7a4be3Structure() : ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.ToStructure(variables.outParamo_ContractPendingJustification);
return result;
}


    public static RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Outputs result = new RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionContractData_Outputs();
result.outParamo_ContractFile = ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.FromStructure(screenModel.outParamo_ContractFile, conf);
result.outParamo_AttachFilesList = screenModel.outParamo_AttachFilesList.ToRestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>(ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.FromStructureDelegate(conf));
result.outParamo_ContractDepositList = screenModel.outParamo_ContractDepositList.ToRestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>(ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.FromStructureDelegate(conf));
result.outParamo_ContractInsuranceList = screenModel.outParamo_ContractInsuranceList.ToRestList<ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure>(ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.FromStructureDelegate(conf));
result.outParamo_ContractAdvancePayment = ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.FromStructure(screenModel.outParamo_ContractAdvancePayment, conf);
result.outParamo_ContractPendingJustification = ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.FromStructure(screenModel.outParamo_ContractPendingJustification, conf);
return result;
}

}
