using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_IsFirstApprover")]
public bool? outParamo_IsFirstApprover;


    public static RESTConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Outputs FromOutputs(IBehaviorsConfiguration conf, bool outParamo_IsFirstApprover) {RESTConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Outputs result = new RESTConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Outputs();
result.outParamo_IsFirstApprover = (bool?) outParamo_IsFirstApprover;
return result;
}


    public static ConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Model ToModel(RESTConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Outputs variables) {ConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Model result = new ConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Model();
result.outParamo_IsFirstApprover = variables == null || variables.outParamo_IsFirstApprover == null ? false : variables.outParamo_IsFirstApprover.Value;
return result;
}


    public static RESTConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Outputs result = new RESTConectaProveedores_j_FoliosSAE_Wb_UploadDocumentsConstructionEdit_DataActionGetApprover_Outputs();
result.outParamo_IsFirstApprover = (bool?) screenModel.outParamo_IsFirstApprover;
return result;
}

}
