using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class ConectaProveedores_c_Proveedor_AccountStatus_DataActionGetSapData_Model {

    public ST_382afa1d8361f400b6ea03403d75e294Structure outParamList;
public decimal outParamTotalenmonedanacional;
public decimal outParamImportetotaldefacturasmonedaextranjera;
public decimal outParamTotalenmonedanacional2;
public decimal outParamImportetotaldefacturasmonedaextranjera2;

}
