using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalsListViewer_ActionDownloadFileWithProposalId_Inputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("i_ProposalId")]
public long? inParami_ProposalId;


    public static RESTConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalsListViewer_ActionDownloadFileWithProposalId_Inputs FromJSON(JObject inputParameters, JsonSerializer settings) {RESTConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalsListViewer_ActionDownloadFileWithProposalId_Inputs result = inputParameters.ToObject<RESTConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalsListViewer_ActionDownloadFileWithProposalId_Inputs>(settings);
return result;
}


    public ConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalsListViewer_ActionDownloadFileWithProposalId_Model ToModel() {ConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalsListViewer_ActionDownloadFileWithProposalId_Model result = new ConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalsListViewer_ActionDownloadFileWithProposalId_Model();
result.inParami_ProposalId = inParami_ProposalId == null ? 0L : inParami_ProposalId.Value;
return result;
}

}
