using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_j_FoliosSAE_Wb_InvoiceSAECUpload_ActionInvoice_OCR_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("ExtractTextOrOcr2")]
public ssConectaProveedores.RestRecords.RESTST_ce06f43cf108d98e4f79c0106fcfd0acStructure outParamExtractTextOrOcr2;
[JsonProperty("ExtractForeignInvoiceDataForUs2")]
public ssConectaProveedores.RestRecords.RESTST_6f620840109ac6f721328b723ec0152cStructure outParamExtractForeignInvoiceDataForUs2;


    public static RESTConectaProveedores_j_FoliosSAE_Wb_InvoiceSAECUpload_ActionInvoice_OCR_Outputs FromOutputs(IBehaviorsConfiguration conf, ST_ce06f43cf108d98e4f79c0106fcfd0acStructure outParamExtractTextOrOcr2, ST_6f620840109ac6f721328b723ec0152cStructure outParamExtractForeignInvoiceDataForUs2) {RESTConectaProveedores_j_FoliosSAE_Wb_InvoiceSAECUpload_ActionInvoice_OCR_Outputs result = new RESTConectaProveedores_j_FoliosSAE_Wb_InvoiceSAECUpload_ActionInvoice_OCR_Outputs();
conf.IncludeBinariesURL = false;
// Write optimized result.outParamExtractTextOrOcr2
result.outParamExtractTextOrOcr2 = ssConectaProveedores.RestRecords.RESTST_ce06f43cf108d98e4f79c0106fcfd0acStructure.FromStructure(new ST_ce06f43cf108d98e4f79c0106fcfd0acStructure(), conf);
// Write the needed fields of the record outParamExtractForeignInvoiceDataForUs2 to the result.outParamExtractForeignInvoiceDataForUs2
result.outParamExtractForeignInvoiceDataForUs2 = new ssConectaProveedores.RestRecords.RESTST_6f620840109ac6f721328b723ec0152cStructure();
result.outParamExtractForeignInvoiceDataForUs2.AttrSuccess = (bool?) outParamExtractForeignInvoiceDataForUs2.ssSuccess;
result.outParamExtractForeignInvoiceDataForUs2.AttrErrorMessage = outParamExtractForeignInvoiceDataForUs2.ssErrorMessage;
result.outParamExtractForeignInvoiceDataForUs2.AttrDocumentType = outParamExtractForeignInvoiceDataForUs2.ssDocumentType;
result.outParamExtractForeignInvoiceDataForUs2.AttrInvoiceNumber = outParamExtractForeignInvoiceDataForUs2.ssInvoiceNumber;
result.outParamExtractForeignInvoiceDataForUs2.AttrSupplierName = outParamExtractForeignInvoiceDataForUs2.ssSupplierName;
result.outParamExtractForeignInvoiceDataForUs2.AttrSupplierTaxId = outParamExtractForeignInvoiceDataForUs2.ssSupplierTaxId;
result.outParamExtractForeignInvoiceDataForUs2.AttrInvoiceDate = outParamExtractForeignInvoiceDataForUs2.ssInvoiceDate;
result.outParamExtractForeignInvoiceDataForUs2.AttrTotalAmount = outParamExtractForeignInvoiceDataForUs2.ssTotalAmount;
result.outParamExtractForeignInvoiceDataForUs2.AttrCurrency = outParamExtractForeignInvoiceDataForUs2.ssCurrency;
result.outParamExtractForeignInvoiceDataForUs2.AttrCustomerNameDetected = outParamExtractForeignInvoiceDataForUs2.ssCustomerNameDetected;
result.outParamExtractForeignInvoiceDataForUs2.AttrCustomerTaxIdDetected = outParamExtractForeignInvoiceDataForUs2.ssCustomerTaxIdDetected;
result.outParamExtractForeignInvoiceDataForUs2.AttrCustomerAddressDetected = outParamExtractForeignInvoiceDataForUs2.ssCustomerAddressDetected;
result.outParamExtractForeignInvoiceDataForUs2.AttrConfidenceScore = (decimal?) outParamExtractForeignInvoiceDataForUs2.ssConfidenceScore;
result.outParamExtractForeignInvoiceDataForUs2.AttrWarningsText = outParamExtractForeignInvoiceDataForUs2.ssWarningsText;
result.outParamExtractForeignInvoiceDataForUs2.AttrRawText = outParamExtractForeignInvoiceDataForUs2.ssRawText;
return result;
}


    

    
}
