using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class ConectaProveedores_c_Requisitions_Wb_RequisitionsPreviewFiles_DataActionGetFilesByRequisitionId_Model {

    public RL_b48e8aa5377b7b15faec0f07ad9facf2 outParamFilesPDF;
public RL_b48e8aa5377b7b15faec0f07ad9facf2 outParamFilesXML;
public RL_b48e8aa5377b7b15faec0f07ad9facf2 outParamOtherFiles;

}
