using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("ValidationReportAuthorizationList")]
public RestList<ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure> outParamValidationReportAuthorizationList;


    public static RESTConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Outputs FromOutputs(IBehaviorsConfiguration conf, RL_2d1a9f1ebd1dae77afe7dba56f4eb06c outParamValidationReportAuthorizationList) {RESTConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Outputs result = new RESTConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Outputs();
// Write the needed fields of the list outParamValidationReportAuthorizationList to the result.outParamValidationReportAuthorizationList
ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure tmpoutParamValidationReportAuthorizationListElement;
if(outParamValidationReportAuthorizationList.Empty) {
// Write the needed fields of the record outParamValidationReportAuthorizationList.CurrentRec to the tmpoutParamValidationReportAuthorizationListElement
tmpoutParamValidationReportAuthorizationListElement = new ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure();
tmpoutParamValidationReportAuthorizationListElement.AttrName = outParamValidationReportAuthorizationList.CurrentRec.ssName;
tmpoutParamValidationReportAuthorizationListElement.AttrField = outParamValidationReportAuthorizationList.CurrentRec.ssField;
tmpoutParamValidationReportAuthorizationListElement.AttrDate = outParamValidationReportAuthorizationList.CurrentRec.ssDate;
tmpoutParamValidationReportAuthorizationListElement.AttrHour = outParamValidationReportAuthorizationList.CurrentRec.ssHour;
result.outParamValidationReportAuthorizationList = new RestList<ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure>(new ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure[] {}, tmpoutParamValidationReportAuthorizationListElement);
} else {
List<ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure>
 tmpoutParamValidationReportAuthorizationList1List = new List<ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure>
();
try {outParamValidationReportAuthorizationList.StartIteration();
while (!(outParamValidationReportAuthorizationList.Eof)) {
// Write the needed fields of the record outParamValidationReportAuthorizationList.CurrentRec to the tmpoutParamValidationReportAuthorizationListElement
tmpoutParamValidationReportAuthorizationListElement = new ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure();
tmpoutParamValidationReportAuthorizationListElement.AttrName = outParamValidationReportAuthorizationList.CurrentRec.ssName;
tmpoutParamValidationReportAuthorizationListElement.AttrField = outParamValidationReportAuthorizationList.CurrentRec.ssField;
tmpoutParamValidationReportAuthorizationListElement.AttrDate = outParamValidationReportAuthorizationList.CurrentRec.ssDate;
tmpoutParamValidationReportAuthorizationListElement.AttrHour = outParamValidationReportAuthorizationList.CurrentRec.ssHour;
tmpoutParamValidationReportAuthorizationList1List.Add(tmpoutParamValidationReportAuthorizationListElement);
outParamValidationReportAuthorizationList.Advance();
}

} finally {
outParamValidationReportAuthorizationList.EndIteration();
}

result.outParamValidationReportAuthorizationList = new RestList<ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure>(tmpoutParamValidationReportAuthorizationList1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure));
}

return result;
}


    public static ConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Model ToModel(RESTConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Outputs variables) {ConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Model result = new ConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Model();
result.outParamValidationReportAuthorizationList = variables == null ? new RL_2d1a9f1ebd1dae77afe7dba56f4eb06c() : RL_2d1a9f1ebd1dae77afe7dba56f4eb06c.FromRestList(variables.outParamValidationReportAuthorizationList, ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure.ToStructure);
return result;
}


    public static RESTConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Outputs result = new RESTConectaProveedores_y_Utils_InvoiceReportPdf_DataActionGetEletronicAuthorizations_Outputs();
result.outParamValidationReportAuthorizationList = screenModel.outParamValidationReportAuthorizationList.ToRestList<ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure>(ssConectaProveedores.RestRecords.RESTST_2667ad63792f2349dc9e4a818559d9ecStructure.FromStructureDelegate(conf));
return result;
}

}
