using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_IsActiveDEV_FlujoRRHH")]
public bool? outParamo_IsActiveDEV_FlujoRRHH;


    public static RESTConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Outputs FromOutputs(IBehaviorsConfiguration conf, bool outParamo_IsActiveDEV_FlujoRRHH) {RESTConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Outputs result = new RESTConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Outputs();
result.outParamo_IsActiveDEV_FlujoRRHH = (bool?) outParamo_IsActiveDEV_FlujoRRHH;
return result;
}


    public static ConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Model ToModel(RESTConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Outputs variables) {ConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Model result = new ConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Model();
result.outParamo_IsActiveDEV_FlujoRRHH = variables == null || variables.outParamo_IsActiveDEV_FlujoRRHH == null ? false : variables.outParamo_IsActiveDEV_FlujoRRHH.Value;
return result;
}


    public static RESTConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Outputs result = new RESTConectaProveedores_c_Requisitions_Wb_IsSpecialOrNormalWF_Popup_DataActionGetSettings_Outputs();
result.outParamo_IsActiveDEV_FlujoRRHH = (bool?) screenModel.outParamo_IsActiveDEV_FlujoRRHH;
return result;
}

}
