using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_FinanceAuthorization")]
public ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_FinanceAuthorization;
[JsonProperty("o_ProofOfForeignResidence")]
public ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_ProofOfForeignResidence;


    public static RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Outputs FromOutputs(IBehaviorsConfiguration conf, ST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_FinanceAuthorization, ST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_ProofOfForeignResidence) {RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Outputs result = new RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Outputs();
// Write the needed fields of the record outParamo_FinanceAuthorization to the result.outParamo_FinanceAuthorization
result.outParamo_FinanceAuthorization = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_FinanceAuthorization.ssOrderContractFile to the result.outParamo_FinanceAuthorization.AttrOrderContractFile
result.outParamo_FinanceAuthorization.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrId = (long?) outParamo_FinanceAuthorization.ssOrderContractFile.ssId;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrOrderId = (long?) outParamo_FinanceAuthorization.ssOrderContractFile.ssOrderId;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_FinanceAuthorization.ssOrderContractFile.ssOrderFileId;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_FinanceAuthorization.ssOrderContractFile.ssContractFileTypeId;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_FinanceAuthorization.ssOrderContractFile.ssAmount;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_FinanceAuthorization.ssOrderContractFile.ssTarif;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrCurrencyId = outParamo_FinanceAuthorization.ssOrderContractFile.ssCurrencyId;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_FinanceAuthorization.ssOrderContractFile.ssDepositTypeId;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_FinanceAuthorization.ssOrderContractFile.ssInsuranceTypeId;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_FinanceAuthorization.ssOrderContractFile.ssAdvancePaymentTypeId;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_FinanceAuthorization.ssOrderContractFile.ssStartBaseDate);
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_FinanceAuthorization.ssOrderContractFile.ssEndBaseDate);
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_FinanceAuthorization.ssOrderContractFile.ssPaymentTermsId;
result.outParamo_FinanceAuthorization.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_FinanceAuthorization.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_FinanceAuthorization.ssOrderFile to the result.outParamo_FinanceAuthorization.AttrOrderFile
result.outParamo_FinanceAuthorization.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
result.outParamo_FinanceAuthorization.AttrOrderFile.AttrId = (long?) outParamo_FinanceAuthorization.ssOrderFile.ssId;
result.outParamo_FinanceAuthorization.AttrOrderFile.AttrFilename = outParamo_FinanceAuthorization.ssOrderFile.ssFilename;
result.outParamo_FinanceAuthorization.AttrOrderFile.AttrVENDOR = outParamo_FinanceAuthorization.ssOrderFile.ssVENDOR;
result.outParamo_FinanceAuthorization.AttrOrderFile.AttrDOC_TYPE = outParamo_FinanceAuthorization.ssOrderFile.ssDOC_TYPE;
result.outParamo_FinanceAuthorization.AttrOrderFile.AttrSAP_OBJECT = outParamo_FinanceAuthorization.ssOrderFile.ssSAP_OBJECT;
result.outParamo_FinanceAuthorization.AttrOrderFile.AttrCreatedBy = outParamo_FinanceAuthorization.ssOrderFile.ssCreatedBy;
result.outParamo_FinanceAuthorization.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_FinanceAuthorization.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_FinanceAuthorization.AttrOrderFile.AttrStorageId = (long?) outParamo_FinanceAuthorization.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_FinanceAuthorization.ssValid to the result.outParamo_FinanceAuthorization.AttrValid
result.outParamo_FinanceAuthorization.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_FinanceAuthorization.AttrValid.AttrIsValid = (bool?) outParamo_FinanceAuthorization.ssValid.ssIsValid;
result.outParamo_FinanceAuthorization.AttrValid.AttrValidationMessage = outParamo_FinanceAuthorization.ssValid.ssValidationMessage;
result.outParamo_FinanceAuthorization.AttrBinary = outParamo_FinanceAuthorization.ssBinary;
// Write the needed fields of the record outParamo_ProofOfForeignResidence to the result.outParamo_ProofOfForeignResidence
result.outParamo_ProofOfForeignResidence = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_ProofOfForeignResidence.ssOrderContractFile to the result.outParamo_ProofOfForeignResidence.AttrOrderContractFile
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrId = (long?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssId;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrOrderId = (long?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssOrderId;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssOrderFileId;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssContractFileTypeId;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssAmount;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssTarif;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrCurrencyId = outParamo_ProofOfForeignResidence.ssOrderContractFile.ssCurrencyId;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssDepositTypeId;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssInsuranceTypeId;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssAdvancePaymentTypeId;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ProofOfForeignResidence.ssOrderContractFile.ssStartBaseDate);
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ProofOfForeignResidence.ssOrderContractFile.ssEndBaseDate);
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssPaymentTermsId;
result.outParamo_ProofOfForeignResidence.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_ProofOfForeignResidence.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_ProofOfForeignResidence.ssOrderFile to the result.outParamo_ProofOfForeignResidence.AttrOrderFile
result.outParamo_ProofOfForeignResidence.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
result.outParamo_ProofOfForeignResidence.AttrOrderFile.AttrId = (long?) outParamo_ProofOfForeignResidence.ssOrderFile.ssId;
result.outParamo_ProofOfForeignResidence.AttrOrderFile.AttrFilename = outParamo_ProofOfForeignResidence.ssOrderFile.ssFilename;
result.outParamo_ProofOfForeignResidence.AttrOrderFile.AttrVENDOR = outParamo_ProofOfForeignResidence.ssOrderFile.ssVENDOR;
result.outParamo_ProofOfForeignResidence.AttrOrderFile.AttrDOC_TYPE = outParamo_ProofOfForeignResidence.ssOrderFile.ssDOC_TYPE;
result.outParamo_ProofOfForeignResidence.AttrOrderFile.AttrSAP_OBJECT = outParamo_ProofOfForeignResidence.ssOrderFile.ssSAP_OBJECT;
result.outParamo_ProofOfForeignResidence.AttrOrderFile.AttrCreatedBy = outParamo_ProofOfForeignResidence.ssOrderFile.ssCreatedBy;
result.outParamo_ProofOfForeignResidence.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ProofOfForeignResidence.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_ProofOfForeignResidence.AttrOrderFile.AttrStorageId = (long?) outParamo_ProofOfForeignResidence.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_ProofOfForeignResidence.ssValid to the result.outParamo_ProofOfForeignResidence.AttrValid
result.outParamo_ProofOfForeignResidence.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_ProofOfForeignResidence.AttrValid.AttrIsValid = (bool?) outParamo_ProofOfForeignResidence.ssValid.ssIsValid;
result.outParamo_ProofOfForeignResidence.AttrValid.AttrValidationMessage = outParamo_ProofOfForeignResidence.ssValid.ssValidationMessage;
result.outParamo_ProofOfForeignResidence.AttrBinary = outParamo_ProofOfForeignResidence.ssBinary;
return result;
}


    public static ConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Model ToModel(RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Outputs variables) {ConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Model result = new ConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Model();
result.outParamo_FinanceAuthorization = variables == null ? new ST_c3df6a1f053620bf8d50da58ff4e41bcStructure() : ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.ToStructure(variables.outParamo_FinanceAuthorization);
result.outParamo_ProofOfForeignResidence = variables == null ? new ST_c3df6a1f053620bf8d50da58ff4e41bcStructure() : ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.ToStructure(variables.outParamo_ProofOfForeignResidence);
return result;
}


    public static RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Outputs result = new RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderFilesList_Outputs();
result.outParamo_FinanceAuthorization = ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.FromStructure(screenModel.outParamo_FinanceAuthorization, conf);
result.outParamo_ProofOfForeignResidence = ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.FromStructure(screenModel.outParamo_ProofOfForeignResidence, conf);
return result;
}

}
