using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_ApprovalProcessIds")]
public string outParamo_ApprovalProcessIds;


    public static RESTConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Outputs FromOutputs(IBehaviorsConfiguration conf, string outParamo_ApprovalProcessIds) {RESTConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Outputs result = new RESTConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Outputs();
result.outParamo_ApprovalProcessIds = outParamo_ApprovalProcessIds;
return result;
}


    public static ConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Model ToModel(RESTConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Outputs variables) {ConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Model result = new ConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Model();
result.outParamo_ApprovalProcessIds = variables == null || variables.outParamo_ApprovalProcessIds == null ? "" : variables.outParamo_ApprovalProcessIds;
return result;
}


    public static RESTConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Outputs result = new RESTConectaProveedores_c_Requisitions_Wb_RequisitionUploadInv_Internal_DataActionGetApprovalProcessIds2_Outputs();
result.outParamo_ApprovalProcessIds = screenModel.outParamo_ApprovalProcessIds;
return result;
}

}
