using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("IsActiveDEV_CostCentersNonActive")]
public bool? outParamIsActiveDEV_CostCentersNonActive;


    public static RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Outputs FromOutputs(IBehaviorsConfiguration conf, bool outParamIsActiveDEV_CostCentersNonActive) {RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Outputs result = new RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Outputs();
// Write optimized result.outParamIsActiveDEV_CostCentersNonActive
result.outParamIsActiveDEV_CostCentersNonActive = (bool?) false;
return result;
}


    public static ConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Model ToModel(RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Outputs variables) {ConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Model result = new ConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Model();
result.outParamIsActiveDEV_CostCentersNonActive = variables == null || variables.outParamIsActiveDEV_CostCentersNonActive == null ? false : variables.outParamIsActiveDEV_CostCentersNonActive.Value;
return result;
}


    public static RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Outputs result = new RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_DataActionGetSettings_Outputs();
result.outParamIsActiveDEV_CostCentersNonActive = (bool?) screenModel.outParamIsActiveDEV_CostCentersNonActive;
return result;
}

}
