using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_IsUserCxP")]
public bool? outParamo_IsUserCxP;


    public static RESTConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Outputs FromOutputs(IBehaviorsConfiguration conf, bool outParamo_IsUserCxP) {RESTConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Outputs result = new RESTConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Outputs();
result.outParamo_IsUserCxP = (bool?) outParamo_IsUserCxP;
return result;
}


    public static ConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Model ToModel(RESTConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Outputs variables) {ConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Model result = new ConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Model();
result.outParamo_IsUserCxP = variables == null || variables.outParamo_IsUserCxP == null ? false : variables.outParamo_IsUserCxP.Value;
return result;
}


    public static RESTConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Outputs result = new RESTConectaProveedores_j_FoliosSAE_ForeignInvoicesPendingValidation_DataActionGetUserData_Outputs();
result.outParamo_IsUserCxP = (bool?) screenModel.outParamo_IsUserCxP;
return result;
}

}
