using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_d_InvoiceAudit_Wb_InvoiceFilesAudit_ActionDownloadZipByStorageIdList_Inputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("StorageIdList")]
public RestList<long> inParamStorageIdList;


    public static RESTConectaProveedores_d_InvoiceAudit_Wb_InvoiceFilesAudit_ActionDownloadZipByStorageIdList_Inputs FromJSON(JObject inputParameters, JsonSerializer settings) {RESTConectaProveedores_d_InvoiceAudit_Wb_InvoiceFilesAudit_ActionDownloadZipByStorageIdList_Inputs result = inputParameters.ToObject<RESTConectaProveedores_d_InvoiceAudit_Wb_InvoiceFilesAudit_ActionDownloadZipByStorageIdList_Inputs>(settings);
return result;
}


    public ConectaProveedores_d_InvoiceAudit_Wb_InvoiceFilesAudit_ActionDownloadZipByStorageIdList_Model ToModel() {ConectaProveedores_d_InvoiceAudit_Wb_InvoiceFilesAudit_ActionDownloadZipByStorageIdList_Model result = new ConectaProveedores_d_InvoiceAudit_Wb_InvoiceFilesAudit_ActionDownloadZipByStorageIdList_Model();
result.inParamStorageIdList = BasicTypeList<long>.FromRestList(inParamStorageIdList);
return result;
}

}
