using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_b_CyA_ApprovalProcessCommissionsLeasing_ApprovalCommissionsandLeases_ActionApproveMultipleProposalLineApprovalLevel_Inputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("i_ProposalLineApprovalLevelIdList")]
public RestList<ssConectaProveedores.RestRecords.RESTRC_474c5c8cc36282ebfc11b03838b11802> inParami_ProposalLineApprovalLevelIdList;


    public static RESTConectaProveedores_b_CyA_ApprovalProcessCommissionsLeasing_ApprovalCommissionsandLeases_ActionApproveMultipleProposalLineApprovalLevel_Inputs FromJSON(JObject inputParameters, JsonSerializer settings) {RESTConectaProveedores_b_CyA_ApprovalProcessCommissionsLeasing_ApprovalCommissionsandLeases_ActionApproveMultipleProposalLineApprovalLevel_Inputs result = inputParameters.ToObject<RESTConectaProveedores_b_CyA_ApprovalProcessCommissionsLeasing_ApprovalCommissionsandLeases_ActionApproveMultipleProposalLineApprovalLevel_Inputs>(settings);
return result;
}


    public ConectaProveedores_b_CyA_ApprovalProcessCommissionsLeasing_ApprovalCommissionsandLeases_ActionApproveMultipleProposalLineApprovalLevel_Model ToModel() {ConectaProveedores_b_CyA_ApprovalProcessCommissionsLeasing_ApprovalCommissionsandLeases_ActionApproveMultipleProposalLineApprovalLevel_Model result = new ConectaProveedores_b_CyA_ApprovalProcessCommissionsLeasing_ApprovalCommissionsandLeases_ActionApproveMultipleProposalLineApprovalLevel_Model();
result.inParami_ProposalLineApprovalLevelIdList = RL_b8bc07441a220c1a5fc88aead339c457.FromRestList(inParami_ProposalLineApprovalLevelIdList, ssConectaProveedores.RestRecords.RESTRC_474c5c8cc36282ebfc11b03838b11802.ToStructure);
return result;
}

}
