using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_Old_ActionGetPaymentMethodDescriptionById_Inputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("PaymentMethodsId")]
public long? inParamPaymentMethodsId;


    public static RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_Old_ActionGetPaymentMethodDescriptionById_Inputs FromJSON(JObject inputParameters, JsonSerializer settings) {RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_Old_ActionGetPaymentMethodDescriptionById_Inputs result = inputParameters.ToObject<RESTConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_Old_ActionGetPaymentMethodDescriptionById_Inputs>(settings);
return result;
}


    public ConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_Old_ActionGetPaymentMethodDescriptionById_Model ToModel() {ConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_Old_ActionGetPaymentMethodDescriptionById_Model result = new ConectaProveedores_d_Invoices_Wb_i_InvoiceAccounting_Old_ActionGetPaymentMethodDescriptionById_Model();
result.inParamPaymentMethodsId = inParamPaymentMethodsId == null ? 0L : inParamPaymentMethodsId.Value;
return result;
}

}
