using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalManualUpload_ActionVerifyAndValidateFilename_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_Output")]
public ssConectaProveedores.RestRecords.RESTST_046fb53ebbe142526d95e87ef1ae9711Structure outParamo_Output;
[JsonProperty("o_ProposalTempData")]
public ssConectaProveedores.RestRecords.RESTST_ba28fce29317fb1a65969ecb0fce5c4bStructure outParamo_ProposalTempData;


    public static RESTConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalManualUpload_ActionVerifyAndValidateFilename_Outputs FromOutputs(IBehaviorsConfiguration conf, ST_046fb53ebbe142526d95e87ef1ae9711Structure outParamo_Output, ST_ba28fce29317fb1a65969ecb0fce5c4bStructure outParamo_ProposalTempData) {RESTConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalManualUpload_ActionVerifyAndValidateFilename_Outputs result = new RESTConectaProveedores_b_CyA_AdminCommissionsLeasing_ProposalManualUpload_ActionVerifyAndValidateFilename_Outputs();
conf.IncludeBinariesURL = false;
// Write the needed fields of the record outParamo_Output to the result.outParamo_Output
result.outParamo_Output = new ssConectaProveedores.RestRecords.RESTST_046fb53ebbe142526d95e87ef1ae9711Structure();
result.outParamo_Output.AttrIsSuccess = (bool?) outParamo_Output.ssIsSuccess;
result.outParamo_Output.AttrMessage = outParamo_Output.ssMessage;
// Write optimized result.outParamo_Output.AttrLines
result.outParamo_Output.AttrLines = (int?) 0;
// Write the needed fields of the record outParamo_ProposalTempData to the result.outParamo_ProposalTempData
result.outParamo_ProposalTempData = new ssConectaProveedores.RestRecords.RESTST_ba28fce29317fb1a65969ecb0fce5c4bStructure();
// Write optimized result.outParamo_ProposalTempData.AttrProposalTypeId
result.outParamo_ProposalTempData.AttrProposalTypeId = (int?) 0;
result.outParamo_ProposalTempData.AttrProposalType = outParamo_ProposalTempData.ssProposalType;
// Write optimized result.outParamo_ProposalTempData.AttrPaymentDate
result.outParamo_ProposalTempData.AttrPaymentDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(new DateTime(1900, 1, 1, 0, 0, 0, DateTimeKind.Utc));
// Write optimized result.outParamo_ProposalTempData.AttrProposalDate
result.outParamo_ProposalTempData.AttrProposalDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(new DateTime(1900, 1, 1, 0, 0, 0, DateTimeKind.Utc));
result.outParamo_ProposalTempData.AttrPaymentDateText = outParamo_ProposalTempData.ssPaymentDateText;
result.outParamo_ProposalTempData.AttrName = outParamo_ProposalTempData.ssName;
result.outParamo_ProposalTempData.AttrBankCode = outParamo_ProposalTempData.ssBankCode;
// Write optimized result.outParamo_ProposalTempData.AttrBankId
result.outParamo_ProposalTempData.AttrBankId = (long?) 0L;
// Write optimized result.outParamo_ProposalTempData.AttrRegion
result.outParamo_ProposalTempData.AttrRegion = "";
// Write optimized result.outParamo_ProposalTempData.AttrRegionId
result.outParamo_ProposalTempData.AttrRegionId = (long?) 0L;
// Write optimized result.outParamo_ProposalTempData.AttrDivisionFI
result.outParamo_ProposalTempData.AttrDivisionFI = "";
result.outParamo_ProposalTempData.AttrTotalProposalLines = (int?) outParamo_ProposalTempData.ssTotalProposalLines;
result.outParamo_ProposalTempData.AttrTotalValueML = (decimal?) outParamo_ProposalTempData.ssTotalValueML;
// Write optimized result.outParamo_ProposalTempData.AttrTotalValueMD
result.outParamo_ProposalTempData.AttrTotalValueMD = (decimal?) 0.0M;
// Write optimized result.outParamo_ProposalTempData.AttrCurrencyId
result.outParamo_ProposalTempData.AttrCurrencyId = "";
result.outParamo_ProposalTempData.AttrCurrencyCode = outParamo_ProposalTempData.ssCurrencyCode;
// Write the needed fields of the list outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList to the result.outParamo_ProposalTempData.AttrCommissionsAndLeasesFileStructList
ssConectaProveedores.RestRecords.RESTST_0a2958ff44247d7464fd88ba7a80597cStructure tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement;
if(outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.Empty) {
// Write the needed fields of the record outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec to the tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement = new ssConectaProveedores.RestRecords.RESTST_0a2958ff44247d7464fd88ba7a80597cStructure();
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrFeContab
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrFeContab = "";
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrEjMes
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrEjMes = "";
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrCuenta = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssCuenta;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrReferencia = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssReferencia;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrNombre1 = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssNombre1;
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrNombre2
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrNombre2 = "";
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrNDoc = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssNDoc;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrImporteEnML = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssImporteEnML;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrML = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssML;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrImporteEnMD = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssImporteEnMD;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrMon = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssMon;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrSoc = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssSoc;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrDiv = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssDiv;
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrLibMayor
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrLibMayor = "";
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrTextoCabDocumento
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrTextoCabDocumento = "";
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrDocComp
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrDocComp = "";
result.outParamo_ProposalTempData.AttrCommissionsAndLeasesFileStructList = new RestList<ssConectaProveedores.RestRecords.RESTST_0a2958ff44247d7464fd88ba7a80597cStructure>(new ssConectaProveedores.RestRecords.RESTST_0a2958ff44247d7464fd88ba7a80597cStructure[] {}, tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement);
} else {
List<ssConectaProveedores.RestRecords.RESTST_0a2958ff44247d7464fd88ba7a80597cStructure>
 tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructList1List = new List<ssConectaProveedores.RestRecords.RESTST_0a2958ff44247d7464fd88ba7a80597cStructure>
();
try {outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.StartIteration();
while (!(outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.Eof)) {
// Write the needed fields of the record outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec to the tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement = new ssConectaProveedores.RestRecords.RESTST_0a2958ff44247d7464fd88ba7a80597cStructure();
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrFeContab
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrFeContab = "";
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrEjMes
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrEjMes = "";
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrCuenta = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssCuenta;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrReferencia = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssReferencia;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrNombre1 = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssNombre1;
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrNombre2
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrNombre2 = "";
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrNDoc = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssNDoc;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrImporteEnML = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssImporteEnML;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrML = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssML;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrImporteEnMD = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssImporteEnMD;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrMon = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssMon;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrSoc = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssSoc;
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrDiv = outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.CurrentRec.ssDiv;
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrLibMayor
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrLibMayor = "";
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrTextoCabDocumento
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrTextoCabDocumento = "";
// Write optimized tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrDocComp
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement.AttrDocComp = "";
tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructList1List.Add(tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructListElement);
outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.Advance();
}

} finally {
outParamo_ProposalTempData.ssCommissionsAndLeasesFileStructList.EndIteration();
}

result.outParamo_ProposalTempData.AttrCommissionsAndLeasesFileStructList = new RestList<ssConectaProveedores.RestRecords.RESTST_0a2958ff44247d7464fd88ba7a80597cStructure>(tmpoutParamo_ProposalTempData_ssCommissionsAndLeasesFileStructList1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTST_0a2958ff44247d7464fd88ba7a80597cStructure));
}

return result;
}


    

    
}
