using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_RequisitionCreatedLog")]
public ssConectaProveedores.RestRecords.RESTST_26711e61541f079fb4510d8f9bfa1e3dStructure outParamo_RequisitionCreatedLog;


    public static RESTConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Outputs FromOutputs(IBehaviorsConfiguration conf, ST_26711e61541f079fb4510d8f9bfa1e3dStructure outParamo_RequisitionCreatedLog) {RESTConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Outputs result = new RESTConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Outputs();
// Write the needed fields of the record outParamo_RequisitionCreatedLog to the result.outParamo_RequisitionCreatedLog
result.outParamo_RequisitionCreatedLog = new ssConectaProveedores.RestRecords.RESTST_26711e61541f079fb4510d8f9bfa1e3dStructure();
result.outParamo_RequisitionCreatedLog.AttrCreatedBy = outParamo_RequisitionCreatedLog.ssCreatedBy;
result.outParamo_RequisitionCreatedLog.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_RequisitionCreatedLog.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_RequisitionCreatedLog.AttrUpdatedBy = outParamo_RequisitionCreatedLog.ssUpdatedBy;
result.outParamo_RequisitionCreatedLog.AttrUpdatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_RequisitionCreatedLog.ssUpdatedOn, conf.DateTimeFormat);
return result;
}


    public static ConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Model ToModel(RESTConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Outputs variables) {ConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Model result = new ConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Model();
result.outParamo_RequisitionCreatedLog = variables == null ? new ST_26711e61541f079fb4510d8f9bfa1e3dStructure() : ssConectaProveedores.RestRecords.RESTST_26711e61541f079fb4510d8f9bfa1e3dStructure.ToStructure(variables.outParamo_RequisitionCreatedLog);
return result;
}


    public static RESTConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Outputs result = new RESTConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Outputs();
result.outParamo_RequisitionCreatedLog = ssConectaProveedores.RestRecords.RESTST_26711e61541f079fb4510d8f9bfa1e3dStructure.FromStructure(screenModel.outParamo_RequisitionCreatedLog, conf);
return result;
}

}
