using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_ContractFile")]
public ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_ContractFile;
[JsonProperty("o_AttachFilesList")]
public RestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure> outParamo_AttachFilesList;
[JsonProperty("o_ContractDepositList")]
public RestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure> outParamo_ContractDepositList;
[JsonProperty("o_ContractInsuranceList")]
public RestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure> outParamo_ContractInsuranceList;
[JsonProperty("o_ContractAdvancePayment")]
public ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_ContractAdvancePayment;
[JsonProperty("o_ContractPendingJustification")]
public ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_ContractPendingJustification;


    public static RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Outputs FromOutputs(IBehaviorsConfiguration conf, ST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_ContractFile, RL_3d745491e03d6d19ccc0e1b33a371ccc outParamo_AttachFilesList, RL_3d745491e03d6d19ccc0e1b33a371ccc outParamo_ContractDepositList, RL_3d745491e03d6d19ccc0e1b33a371ccc outParamo_ContractInsuranceList, ST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_ContractAdvancePayment, ST_c3df6a1f053620bf8d50da58ff4e41bcStructure outParamo_ContractPendingJustification) {RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Outputs result = new RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Outputs();
// Write the needed fields of the record outParamo_ContractFile to the result.outParamo_ContractFile
result.outParamo_ContractFile = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_ContractFile.ssOrderContractFile to the result.outParamo_ContractFile.AttrOrderContractFile
result.outParamo_ContractFile.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
result.outParamo_ContractFile.AttrOrderContractFile.AttrId = (long?) outParamo_ContractFile.ssOrderContractFile.ssId;
result.outParamo_ContractFile.AttrOrderContractFile.AttrOrderId = (long?) outParamo_ContractFile.ssOrderContractFile.ssOrderId;
result.outParamo_ContractFile.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_ContractFile.ssOrderContractFile.ssOrderFileId;
result.outParamo_ContractFile.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_ContractFile.ssOrderContractFile.ssContractFileTypeId;
result.outParamo_ContractFile.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_ContractFile.ssOrderContractFile.ssAmount;
result.outParamo_ContractFile.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_ContractFile.ssOrderContractFile.ssTarif;
result.outParamo_ContractFile.AttrOrderContractFile.AttrCurrencyId = outParamo_ContractFile.ssOrderContractFile.ssCurrencyId;
result.outParamo_ContractFile.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_ContractFile.ssOrderContractFile.ssDepositTypeId;
result.outParamo_ContractFile.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractFile.ssOrderContractFile.ssInsuranceTypeId;
result.outParamo_ContractFile.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractFile.ssOrderContractFile.ssAdvancePaymentTypeId;
result.outParamo_ContractFile.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractFile.ssOrderContractFile.ssStartBaseDate);
result.outParamo_ContractFile.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractFile.ssOrderContractFile.ssEndBaseDate);
result.outParamo_ContractFile.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_ContractFile.ssOrderContractFile.ssPaymentTermsId;
result.outParamo_ContractFile.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_ContractFile.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_ContractFile.ssOrderFile to the result.outParamo_ContractFile.AttrOrderFile
result.outParamo_ContractFile.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
result.outParamo_ContractFile.AttrOrderFile.AttrId = (long?) outParamo_ContractFile.ssOrderFile.ssId;
result.outParamo_ContractFile.AttrOrderFile.AttrFilename = outParamo_ContractFile.ssOrderFile.ssFilename;
result.outParamo_ContractFile.AttrOrderFile.AttrVENDOR = outParamo_ContractFile.ssOrderFile.ssVENDOR;
result.outParamo_ContractFile.AttrOrderFile.AttrDOC_TYPE = outParamo_ContractFile.ssOrderFile.ssDOC_TYPE;
result.outParamo_ContractFile.AttrOrderFile.AttrSAP_OBJECT = outParamo_ContractFile.ssOrderFile.ssSAP_OBJECT;
result.outParamo_ContractFile.AttrOrderFile.AttrCreatedBy = outParamo_ContractFile.ssOrderFile.ssCreatedBy;
result.outParamo_ContractFile.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractFile.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_ContractFile.AttrOrderFile.AttrStorageId = (long?) outParamo_ContractFile.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractFile.ssValid to the result.outParamo_ContractFile.AttrValid
result.outParamo_ContractFile.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_ContractFile.AttrValid.AttrIsValid = (bool?) outParamo_ContractFile.ssValid.ssIsValid;
result.outParamo_ContractFile.AttrValid.AttrValidationMessage = outParamo_ContractFile.ssValid.ssValidationMessage;
result.outParamo_ContractFile.AttrBinary = outParamo_ContractFile.ssBinary;
// Write the needed fields of the list outParamo_AttachFilesList to the result.outParamo_AttachFilesList
ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure tmpoutParamo_AttachFilesListElement;
if(outParamo_AttachFilesList.Empty) {
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec to the tmpoutParamo_AttachFilesListElement
tmpoutParamo_AttachFilesListElement = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssOrderContractFile to the tmpoutParamo_AttachFilesListElement.AttrOrderContractFile
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrOrderId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssOrderId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssOrderFileId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssContractFileTypeId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssAmount;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssTarif;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrCurrencyId = outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssCurrencyId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssDepositTypeId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssInsuranceTypeId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssAdvancePaymentTypeId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssStartBaseDate);
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssEndBaseDate);
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssPaymentTermsId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssOrderFile to the tmpoutParamo_AttachFilesListElement.AttrOrderFile
tmpoutParamo_AttachFilesListElement.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssId;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrFilename = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssFilename;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrVENDOR = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssVENDOR;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrDOC_TYPE = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssDOC_TYPE;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrSAP_OBJECT = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssSAP_OBJECT;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrCreatedBy = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssCreatedBy;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrStorageId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssValid to the tmpoutParamo_AttachFilesListElement.AttrValid
tmpoutParamo_AttachFilesListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_AttachFilesListElement.AttrValid.AttrIsValid = (bool?) outParamo_AttachFilesList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_AttachFilesListElement.AttrValid.AttrValidationMessage = outParamo_AttachFilesList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_AttachFilesListElement.AttrBinary = outParamo_AttachFilesList.CurrentRec.ssBinary;
result.outParamo_AttachFilesList = new RestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>(new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure[] {}, tmpoutParamo_AttachFilesListElement);
} else {
List<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>
 tmpoutParamo_AttachFilesList1List = new List<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>
();
try {outParamo_AttachFilesList.StartIteration();
while (!(outParamo_AttachFilesList.Eof)) {
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec to the tmpoutParamo_AttachFilesListElement
tmpoutParamo_AttachFilesListElement = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssOrderContractFile to the tmpoutParamo_AttachFilesListElement.AttrOrderContractFile
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrOrderId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssOrderId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssOrderFileId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssContractFileTypeId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssAmount;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssTarif;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrCurrencyId = outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssCurrencyId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssDepositTypeId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssInsuranceTypeId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssAdvancePaymentTypeId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssStartBaseDate);
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssEndBaseDate);
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssPaymentTermsId;
tmpoutParamo_AttachFilesListElement.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_AttachFilesList.CurrentRec.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssOrderFile to the tmpoutParamo_AttachFilesListElement.AttrOrderFile
tmpoutParamo_AttachFilesListElement.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssId;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrFilename = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssFilename;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrVENDOR = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssVENDOR;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrDOC_TYPE = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssDOC_TYPE;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrSAP_OBJECT = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssSAP_OBJECT;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrCreatedBy = outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssCreatedBy;
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_AttachFilesListElement.AttrOrderFile.AttrStorageId = (long?) outParamo_AttachFilesList.CurrentRec.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_AttachFilesList.CurrentRec.ssValid to the tmpoutParamo_AttachFilesListElement.AttrValid
tmpoutParamo_AttachFilesListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_AttachFilesListElement.AttrValid.AttrIsValid = (bool?) outParamo_AttachFilesList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_AttachFilesListElement.AttrValid.AttrValidationMessage = outParamo_AttachFilesList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_AttachFilesListElement.AttrBinary = outParamo_AttachFilesList.CurrentRec.ssBinary;
tmpoutParamo_AttachFilesList1List.Add(tmpoutParamo_AttachFilesListElement);
outParamo_AttachFilesList.Advance();
}

} finally {
outParamo_AttachFilesList.EndIteration();
}

result.outParamo_AttachFilesList = new RestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>(tmpoutParamo_AttachFilesList1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure));
}

// Write the needed fields of the list outParamo_ContractDepositList to the result.outParamo_ContractDepositList
ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure tmpoutParamo_ContractDepositListElement;
if(outParamo_ContractDepositList.Empty) {
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec to the tmpoutParamo_ContractDepositListElement
tmpoutParamo_ContractDepositListElement = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssOrderContractFile to the tmpoutParamo_ContractDepositListElement.AttrOrderContractFile
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrOrderId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssOrderId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssOrderFileId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssContractFileTypeId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssAmount;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssTarif;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrCurrencyId = outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssCurrencyId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssDepositTypeId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssInsuranceTypeId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssAdvancePaymentTypeId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssStartBaseDate);
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssEndBaseDate);
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssPaymentTermsId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssOrderFile to the tmpoutParamo_ContractDepositListElement.AttrOrderFile
tmpoutParamo_ContractDepositListElement.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssId;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrFilename = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssFilename;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrVENDOR = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssVENDOR;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrDOC_TYPE = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssDOC_TYPE;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrSAP_OBJECT = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssSAP_OBJECT;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrCreatedBy = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssCreatedBy;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrStorageId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssValid to the tmpoutParamo_ContractDepositListElement.AttrValid
tmpoutParamo_ContractDepositListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_ContractDepositListElement.AttrValid.AttrIsValid = (bool?) outParamo_ContractDepositList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_ContractDepositListElement.AttrValid.AttrValidationMessage = outParamo_ContractDepositList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_ContractDepositListElement.AttrBinary = outParamo_ContractDepositList.CurrentRec.ssBinary;
result.outParamo_ContractDepositList = new RestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>(new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure[] {}, tmpoutParamo_ContractDepositListElement);
} else {
List<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>
 tmpoutParamo_ContractDepositList1List = new List<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>
();
try {outParamo_ContractDepositList.StartIteration();
while (!(outParamo_ContractDepositList.Eof)) {
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec to the tmpoutParamo_ContractDepositListElement
tmpoutParamo_ContractDepositListElement = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssOrderContractFile to the tmpoutParamo_ContractDepositListElement.AttrOrderContractFile
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrOrderId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssOrderId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssOrderFileId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssContractFileTypeId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssAmount;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssTarif;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrCurrencyId = outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssCurrencyId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssDepositTypeId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssInsuranceTypeId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssAdvancePaymentTypeId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssStartBaseDate);
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssEndBaseDate);
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssPaymentTermsId;
tmpoutParamo_ContractDepositListElement.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_ContractDepositList.CurrentRec.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssOrderFile to the tmpoutParamo_ContractDepositListElement.AttrOrderFile
tmpoutParamo_ContractDepositListElement.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssId;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrFilename = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssFilename;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrVENDOR = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssVENDOR;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrDOC_TYPE = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssDOC_TYPE;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrSAP_OBJECT = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssSAP_OBJECT;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrCreatedBy = outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssCreatedBy;
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_ContractDepositListElement.AttrOrderFile.AttrStorageId = (long?) outParamo_ContractDepositList.CurrentRec.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractDepositList.CurrentRec.ssValid to the tmpoutParamo_ContractDepositListElement.AttrValid
tmpoutParamo_ContractDepositListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_ContractDepositListElement.AttrValid.AttrIsValid = (bool?) outParamo_ContractDepositList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_ContractDepositListElement.AttrValid.AttrValidationMessage = outParamo_ContractDepositList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_ContractDepositListElement.AttrBinary = outParamo_ContractDepositList.CurrentRec.ssBinary;
tmpoutParamo_ContractDepositList1List.Add(tmpoutParamo_ContractDepositListElement);
outParamo_ContractDepositList.Advance();
}

} finally {
outParamo_ContractDepositList.EndIteration();
}

result.outParamo_ContractDepositList = new RestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>(tmpoutParamo_ContractDepositList1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure));
}

// Write the needed fields of the list outParamo_ContractInsuranceList to the result.outParamo_ContractInsuranceList
ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure tmpoutParamo_ContractInsuranceListElement;
if(outParamo_ContractInsuranceList.Empty) {
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec to the tmpoutParamo_ContractInsuranceListElement
tmpoutParamo_ContractInsuranceListElement = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile to the tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrOrderId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssOrderId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssOrderFileId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssContractFileTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssAmount;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssTarif;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrCurrencyId = outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssCurrencyId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssDepositTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssInsuranceTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssAdvancePaymentTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssStartBaseDate);
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssEndBaseDate);
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssPaymentTermsId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssOrderFile to the tmpoutParamo_ContractInsuranceListElement.AttrOrderFile
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrFilename = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssFilename;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrVENDOR = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssVENDOR;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrDOC_TYPE = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssDOC_TYPE;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrSAP_OBJECT = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssSAP_OBJECT;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrCreatedBy = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssCreatedBy;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrStorageId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssValid to the tmpoutParamo_ContractInsuranceListElement.AttrValid
tmpoutParamo_ContractInsuranceListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_ContractInsuranceListElement.AttrValid.AttrIsValid = (bool?) outParamo_ContractInsuranceList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_ContractInsuranceListElement.AttrValid.AttrValidationMessage = outParamo_ContractInsuranceList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_ContractInsuranceListElement.AttrBinary = outParamo_ContractInsuranceList.CurrentRec.ssBinary;
result.outParamo_ContractInsuranceList = new RestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>(new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure[] {}, tmpoutParamo_ContractInsuranceListElement);
} else {
List<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>
 tmpoutParamo_ContractInsuranceList1List = new List<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>
();
try {outParamo_ContractInsuranceList.StartIteration();
while (!(outParamo_ContractInsuranceList.Eof)) {
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec to the tmpoutParamo_ContractInsuranceListElement
tmpoutParamo_ContractInsuranceListElement = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile to the tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrOrderId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssOrderId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssOrderFileId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssContractFileTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssAmount;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssTarif;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrCurrencyId = outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssCurrencyId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssDepositTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssInsuranceTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssAdvancePaymentTypeId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssStartBaseDate);
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssEndBaseDate);
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssPaymentTermsId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_ContractInsuranceList.CurrentRec.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssOrderFile to the tmpoutParamo_ContractInsuranceListElement.AttrOrderFile
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssId;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrFilename = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssFilename;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrVENDOR = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssVENDOR;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrDOC_TYPE = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssDOC_TYPE;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrSAP_OBJECT = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssSAP_OBJECT;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrCreatedBy = outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssCreatedBy;
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_ContractInsuranceListElement.AttrOrderFile.AttrStorageId = (long?) outParamo_ContractInsuranceList.CurrentRec.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractInsuranceList.CurrentRec.ssValid to the tmpoutParamo_ContractInsuranceListElement.AttrValid
tmpoutParamo_ContractInsuranceListElement.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
tmpoutParamo_ContractInsuranceListElement.AttrValid.AttrIsValid = (bool?) outParamo_ContractInsuranceList.CurrentRec.ssValid.ssIsValid;
tmpoutParamo_ContractInsuranceListElement.AttrValid.AttrValidationMessage = outParamo_ContractInsuranceList.CurrentRec.ssValid.ssValidationMessage;
tmpoutParamo_ContractInsuranceListElement.AttrBinary = outParamo_ContractInsuranceList.CurrentRec.ssBinary;
tmpoutParamo_ContractInsuranceList1List.Add(tmpoutParamo_ContractInsuranceListElement);
outParamo_ContractInsuranceList.Advance();
}

} finally {
outParamo_ContractInsuranceList.EndIteration();
}

result.outParamo_ContractInsuranceList = new RestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>(tmpoutParamo_ContractInsuranceList1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure));
}

// Write the needed fields of the record outParamo_ContractAdvancePayment to the result.outParamo_ContractAdvancePayment
result.outParamo_ContractAdvancePayment = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_ContractAdvancePayment.ssOrderContractFile to the result.outParamo_ContractAdvancePayment.AttrOrderContractFile
result.outParamo_ContractAdvancePayment.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrId = (long?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssId;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrOrderId = (long?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssOrderId;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssOrderFileId;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssContractFileTypeId;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssAmount;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssTarif;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrCurrencyId = outParamo_ContractAdvancePayment.ssOrderContractFile.ssCurrencyId;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssDepositTypeId;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssInsuranceTypeId;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssAdvancePaymentTypeId;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractAdvancePayment.ssOrderContractFile.ssStartBaseDate);
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractAdvancePayment.ssOrderContractFile.ssEndBaseDate);
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssPaymentTermsId;
result.outParamo_ContractAdvancePayment.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_ContractAdvancePayment.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_ContractAdvancePayment.ssOrderFile to the result.outParamo_ContractAdvancePayment.AttrOrderFile
result.outParamo_ContractAdvancePayment.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
result.outParamo_ContractAdvancePayment.AttrOrderFile.AttrId = (long?) outParamo_ContractAdvancePayment.ssOrderFile.ssId;
result.outParamo_ContractAdvancePayment.AttrOrderFile.AttrFilename = outParamo_ContractAdvancePayment.ssOrderFile.ssFilename;
result.outParamo_ContractAdvancePayment.AttrOrderFile.AttrVENDOR = outParamo_ContractAdvancePayment.ssOrderFile.ssVENDOR;
result.outParamo_ContractAdvancePayment.AttrOrderFile.AttrDOC_TYPE = outParamo_ContractAdvancePayment.ssOrderFile.ssDOC_TYPE;
result.outParamo_ContractAdvancePayment.AttrOrderFile.AttrSAP_OBJECT = outParamo_ContractAdvancePayment.ssOrderFile.ssSAP_OBJECT;
result.outParamo_ContractAdvancePayment.AttrOrderFile.AttrCreatedBy = outParamo_ContractAdvancePayment.ssOrderFile.ssCreatedBy;
result.outParamo_ContractAdvancePayment.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractAdvancePayment.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_ContractAdvancePayment.AttrOrderFile.AttrStorageId = (long?) outParamo_ContractAdvancePayment.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractAdvancePayment.ssValid to the result.outParamo_ContractAdvancePayment.AttrValid
result.outParamo_ContractAdvancePayment.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_ContractAdvancePayment.AttrValid.AttrIsValid = (bool?) outParamo_ContractAdvancePayment.ssValid.ssIsValid;
result.outParamo_ContractAdvancePayment.AttrValid.AttrValidationMessage = outParamo_ContractAdvancePayment.ssValid.ssValidationMessage;
result.outParamo_ContractAdvancePayment.AttrBinary = outParamo_ContractAdvancePayment.ssBinary;
// Write the needed fields of the record outParamo_ContractPendingJustification to the result.outParamo_ContractPendingJustification
result.outParamo_ContractPendingJustification = new ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure();
// Write the needed fields of the record outParamo_ContractPendingJustification.ssOrderContractFile to the result.outParamo_ContractPendingJustification.AttrOrderContractFile
result.outParamo_ContractPendingJustification.AttrOrderContractFile = new ssConectaProveedores.RestRecords.RESTEN_17538b35348920159ed0ee43b3fb2b50EntityRecord();
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrId = (long?) outParamo_ContractPendingJustification.ssOrderContractFile.ssId;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrOrderId = (long?) outParamo_ContractPendingJustification.ssOrderContractFile.ssOrderId;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrOrderFileId = (long?) outParamo_ContractPendingJustification.ssOrderContractFile.ssOrderFileId;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrContractFileTypeId = (int?) outParamo_ContractPendingJustification.ssOrderContractFile.ssContractFileTypeId;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrAmount = (decimal?) outParamo_ContractPendingJustification.ssOrderContractFile.ssAmount;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrTarif = (decimal?) outParamo_ContractPendingJustification.ssOrderContractFile.ssTarif;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrCurrencyId = outParamo_ContractPendingJustification.ssOrderContractFile.ssCurrencyId;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrDepositTypeId = (int?) outParamo_ContractPendingJustification.ssOrderContractFile.ssDepositTypeId;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrInsuranceTypeId = (int?) outParamo_ContractPendingJustification.ssOrderContractFile.ssInsuranceTypeId;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ContractPendingJustification.ssOrderContractFile.ssAdvancePaymentTypeId;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrStartBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractPendingJustification.ssOrderContractFile.ssStartBaseDate);
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrEndBaseDate = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_ContractPendingJustification.ssOrderContractFile.ssEndBaseDate);
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrPaymentTermsId = (long?) outParamo_ContractPendingJustification.ssOrderContractFile.ssPaymentTermsId;
result.outParamo_ContractPendingJustification.AttrOrderContractFile.AttrIsForVendorUpload = (bool?) outParamo_ContractPendingJustification.ssOrderContractFile.ssIsForVendorUpload;
// Write the needed fields of the record outParamo_ContractPendingJustification.ssOrderFile to the result.outParamo_ContractPendingJustification.AttrOrderFile
result.outParamo_ContractPendingJustification.AttrOrderFile = new ssConectaProveedores.RestRecords.RESTEN_096339be3ef098b3762e8897e3a1c095EntityRecord();
result.outParamo_ContractPendingJustification.AttrOrderFile.AttrId = (long?) outParamo_ContractPendingJustification.ssOrderFile.ssId;
result.outParamo_ContractPendingJustification.AttrOrderFile.AttrFilename = outParamo_ContractPendingJustification.ssOrderFile.ssFilename;
result.outParamo_ContractPendingJustification.AttrOrderFile.AttrVENDOR = outParamo_ContractPendingJustification.ssOrderFile.ssVENDOR;
result.outParamo_ContractPendingJustification.AttrOrderFile.AttrDOC_TYPE = outParamo_ContractPendingJustification.ssOrderFile.ssDOC_TYPE;
result.outParamo_ContractPendingJustification.AttrOrderFile.AttrSAP_OBJECT = outParamo_ContractPendingJustification.ssOrderFile.ssSAP_OBJECT;
result.outParamo_ContractPendingJustification.AttrOrderFile.AttrCreatedBy = outParamo_ContractPendingJustification.ssOrderFile.ssCreatedBy;
result.outParamo_ContractPendingJustification.AttrOrderFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ContractPendingJustification.ssOrderFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_ContractPendingJustification.AttrOrderFile.AttrStorageId = (long?) outParamo_ContractPendingJustification.ssOrderFile.ssStorageId;
// Write the needed fields of the record outParamo_ContractPendingJustification.ssValid to the result.outParamo_ContractPendingJustification.AttrValid
result.outParamo_ContractPendingJustification.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_ContractPendingJustification.AttrValid.AttrIsValid = (bool?) outParamo_ContractPendingJustification.ssValid.ssIsValid;
result.outParamo_ContractPendingJustification.AttrValid.AttrValidationMessage = outParamo_ContractPendingJustification.ssValid.ssValidationMessage;
result.outParamo_ContractPendingJustification.AttrBinary = outParamo_ContractPendingJustification.ssBinary;
return result;
}


    public static ConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Model ToModel(RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Outputs variables) {ConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Model result = new ConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Model();
result.outParamo_ContractFile = variables == null ? new ST_c3df6a1f053620bf8d50da58ff4e41bcStructure() : ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.ToStructure(variables.outParamo_ContractFile);
result.outParamo_AttachFilesList = variables == null ? new RL_3d745491e03d6d19ccc0e1b33a371ccc() : RL_3d745491e03d6d19ccc0e1b33a371ccc.FromRestList(variables.outParamo_AttachFilesList, ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.ToStructure);
result.outParamo_ContractDepositList = variables == null ? new RL_3d745491e03d6d19ccc0e1b33a371ccc() : RL_3d745491e03d6d19ccc0e1b33a371ccc.FromRestList(variables.outParamo_ContractDepositList, ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.ToStructure);
result.outParamo_ContractInsuranceList = variables == null ? new RL_3d745491e03d6d19ccc0e1b33a371ccc() : RL_3d745491e03d6d19ccc0e1b33a371ccc.FromRestList(variables.outParamo_ContractInsuranceList, ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.ToStructure);
result.outParamo_ContractAdvancePayment = variables == null ? new ST_c3df6a1f053620bf8d50da58ff4e41bcStructure() : ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.ToStructure(variables.outParamo_ContractAdvancePayment);
result.outParamo_ContractPendingJustification = variables == null ? new ST_c3df6a1f053620bf8d50da58ff4e41bcStructure() : ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.ToStructure(variables.outParamo_ContractPendingJustification);
return result;
}


    public static RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Outputs result = new RESTConectaProveedores_e_Orders_Wb_OrderDetailPaymentInformation_DataActionGetOrderContractData_Outputs();
result.outParamo_ContractFile = ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.FromStructure(screenModel.outParamo_ContractFile, conf);
result.outParamo_AttachFilesList = screenModel.outParamo_AttachFilesList.ToRestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>(ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.FromStructureDelegate(conf));
result.outParamo_ContractDepositList = screenModel.outParamo_ContractDepositList.ToRestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>(ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.FromStructureDelegate(conf));
result.outParamo_ContractInsuranceList = screenModel.outParamo_ContractInsuranceList.ToRestList<ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure>(ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.FromStructureDelegate(conf));
result.outParamo_ContractAdvancePayment = ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.FromStructure(screenModel.outParamo_ContractAdvancePayment, conf);
result.outParamo_ContractPendingJustification = ssConectaProveedores.RestRecords.RESTST_c3df6a1f053620bf8d50da58ff4e41bcStructure.FromStructure(screenModel.outParamo_ContractPendingJustification, conf);
return result;
}

}
