using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_AdvWithoutInvoice")]
public ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_AdvWithoutInvoice;


    public static RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Outputs FromOutputs(IBehaviorsConfiguration conf, ST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_AdvWithoutInvoice) {RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Outputs result = new RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Outputs();
// Write the needed fields of the record outParamo_AdvWithoutInvoice to the result.outParamo_AdvWithoutInvoice
result.outParamo_AdvWithoutInvoice = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_AdvWithoutInvoice.ssRequisitionContractFile to the result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrId = (long?) outParamo_AdvWithoutInvoice.ssRequisitionContractFile.ssId;
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_AdvWithoutInvoice.ssRequisitionContractFile.ssRequisitionId;
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_AdvWithoutInvoice.ssRequisitionContractFile.ssRequisitionFileId;
// Write optimized result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrContractFileTypeId
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) 0;
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_AdvWithoutInvoice.ssRequisitionContractFile.ssAmount;
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrCurrencyId = outParamo_AdvWithoutInvoice.ssRequisitionContractFile.ssCurrencyId;
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_AdvWithoutInvoice.ssRequisitionContractFile.ssDepositTypeId;
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_AdvWithoutInvoice.ssRequisitionContractFile.ssInsuranceTypeId;
result.outParamo_AdvWithoutInvoice.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_AdvWithoutInvoice.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_AdvWithoutInvoice.ssRequisitionFile to the result.outParamo_AdvWithoutInvoice.AttrRequisitionFile
result.outParamo_AdvWithoutInvoice.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
result.outParamo_AdvWithoutInvoice.AttrRequisitionFile.AttrId = (long?) outParamo_AdvWithoutInvoice.ssRequisitionFile.ssId;
result.outParamo_AdvWithoutInvoice.AttrRequisitionFile.AttrFilename = outParamo_AdvWithoutInvoice.ssRequisitionFile.ssFilename;
result.outParamo_AdvWithoutInvoice.AttrRequisitionFile.AttrVENDOR = outParamo_AdvWithoutInvoice.ssRequisitionFile.ssVENDOR;
result.outParamo_AdvWithoutInvoice.AttrRequisitionFile.AttrDOC_TYPE = outParamo_AdvWithoutInvoice.ssRequisitionFile.ssDOC_TYPE;
result.outParamo_AdvWithoutInvoice.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_AdvWithoutInvoice.ssRequisitionFile.ssSAP_OBJECT;
result.outParamo_AdvWithoutInvoice.AttrRequisitionFile.AttrCreatedBy = outParamo_AdvWithoutInvoice.ssRequisitionFile.ssCreatedBy;
result.outParamo_AdvWithoutInvoice.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_AdvWithoutInvoice.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_AdvWithoutInvoice.AttrRequisitionFile.AttrStorageId = (long?) outParamo_AdvWithoutInvoice.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_AdvWithoutInvoice.ssValid to the result.outParamo_AdvWithoutInvoice.AttrValid
result.outParamo_AdvWithoutInvoice.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_AdvWithoutInvoice.AttrValid.AttrIsValid = (bool?) outParamo_AdvWithoutInvoice.ssValid.ssIsValid;
result.outParamo_AdvWithoutInvoice.AttrValid.AttrValidationMessage = outParamo_AdvWithoutInvoice.ssValid.ssValidationMessage;
result.outParamo_AdvWithoutInvoice.AttrBinary = outParamo_AdvWithoutInvoice.ssBinary;
result.outParamo_AdvWithoutInvoice.AttrBigUploadfileId = (long?) outParamo_AdvWithoutInvoice.ssBigUploadfileId;
return result;
}


    public static ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Model ToModel(RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Outputs variables) {ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Model result = new ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Model();
result.outParamo_AdvWithoutInvoice = variables == null ? new ST_26b16bea631cbd94cf555acb5c7a4be3Structure() : ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.ToStructure(variables.outParamo_AdvWithoutInvoice);
return result;
}


    public static RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Outputs result = new RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetAdvWithoutInvoiceData_Outputs();
result.outParamo_AdvWithoutInvoice = ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.FromStructure(screenModel.outParamo_AdvWithoutInvoice, conf);
return result;
}

}
