using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("AllowImport")]
public bool? outParamAllowImport;


    public static RESTConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Outputs FromOutputs(IBehaviorsConfiguration conf, bool outParamAllowImport) {RESTConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Outputs result = new RESTConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Outputs();
result.outParamAllowImport = (bool?) outParamAllowImport;
return result;
}


    public static ConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Model ToModel(RESTConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Outputs variables) {ConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Model result = new ConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Model();
result.outParamAllowImport = variables == null || variables.outParamAllowImport == null ? false : variables.outParamAllowImport.Value;
return result;
}


    public static RESTConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Outputs result = new RESTConectaProveedores_h_OrderDistributionConfig_OrderDistributionConfig_DataActionGetSettings_Outputs();
result.outParamAllowImport = (bool?) screenModel.outParamAllowImport;
return result;
}

}
