using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class ConectaProveedores_c_Requisitions_Wb_RequisitionsCreatedOrUpdatedBy_DataActionGetsRequisitionsData_Model {

    public ST_26711e61541f079fb4510d8f9bfa1e3dStructure outParamo_RequisitionCreatedLog;

}
