using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_FinanceAuthorization")]
public ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_FinanceAuthorization;
[JsonProperty("o_ProofOfForeignResidence")]
public ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_ProofOfForeignResidence;


    public static RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Outputs FromOutputs(IBehaviorsConfiguration conf, ST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_FinanceAuthorization, ST_26b16bea631cbd94cf555acb5c7a4be3Structure outParamo_ProofOfForeignResidence) {RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Outputs result = new RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Outputs();
// Write the needed fields of the record outParamo_FinanceAuthorization to the result.outParamo_FinanceAuthorization
result.outParamo_FinanceAuthorization = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_FinanceAuthorization.ssRequisitionContractFile to the result.outParamo_FinanceAuthorization.AttrRequisitionContractFile
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile.AttrId = (long?) outParamo_FinanceAuthorization.ssRequisitionContractFile.ssId;
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_FinanceAuthorization.ssRequisitionContractFile.ssRequisitionId;
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_FinanceAuthorization.ssRequisitionContractFile.ssRequisitionFileId;
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_FinanceAuthorization.ssRequisitionContractFile.ssContractFileTypeId;
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_FinanceAuthorization.ssRequisitionContractFile.ssAmount;
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile.AttrCurrencyId = outParamo_FinanceAuthorization.ssRequisitionContractFile.ssCurrencyId;
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_FinanceAuthorization.ssRequisitionContractFile.ssDepositTypeId;
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_FinanceAuthorization.ssRequisitionContractFile.ssInsuranceTypeId;
result.outParamo_FinanceAuthorization.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_FinanceAuthorization.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_FinanceAuthorization.ssRequisitionFile to the result.outParamo_FinanceAuthorization.AttrRequisitionFile
result.outParamo_FinanceAuthorization.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
result.outParamo_FinanceAuthorization.AttrRequisitionFile.AttrId = (long?) outParamo_FinanceAuthorization.ssRequisitionFile.ssId;
result.outParamo_FinanceAuthorization.AttrRequisitionFile.AttrFilename = outParamo_FinanceAuthorization.ssRequisitionFile.ssFilename;
result.outParamo_FinanceAuthorization.AttrRequisitionFile.AttrVENDOR = outParamo_FinanceAuthorization.ssRequisitionFile.ssVENDOR;
result.outParamo_FinanceAuthorization.AttrRequisitionFile.AttrDOC_TYPE = outParamo_FinanceAuthorization.ssRequisitionFile.ssDOC_TYPE;
result.outParamo_FinanceAuthorization.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_FinanceAuthorization.ssRequisitionFile.ssSAP_OBJECT;
result.outParamo_FinanceAuthorization.AttrRequisitionFile.AttrCreatedBy = outParamo_FinanceAuthorization.ssRequisitionFile.ssCreatedBy;
result.outParamo_FinanceAuthorization.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_FinanceAuthorization.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_FinanceAuthorization.AttrRequisitionFile.AttrStorageId = (long?) outParamo_FinanceAuthorization.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_FinanceAuthorization.ssValid to the result.outParamo_FinanceAuthorization.AttrValid
result.outParamo_FinanceAuthorization.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_FinanceAuthorization.AttrValid.AttrIsValid = (bool?) outParamo_FinanceAuthorization.ssValid.ssIsValid;
result.outParamo_FinanceAuthorization.AttrValid.AttrValidationMessage = outParamo_FinanceAuthorization.ssValid.ssValidationMessage;
result.outParamo_FinanceAuthorization.AttrBinary = outParamo_FinanceAuthorization.ssBinary;
result.outParamo_FinanceAuthorization.AttrBigUploadfileId = (long?) outParamo_FinanceAuthorization.ssBigUploadfileId;
// Write the needed fields of the record outParamo_ProofOfForeignResidence to the result.outParamo_ProofOfForeignResidence
result.outParamo_ProofOfForeignResidence = new ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure();
// Write the needed fields of the record outParamo_ProofOfForeignResidence.ssRequisitionContractFile to the result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile = new ssConectaProveedores.RestRecords.RESTEN_aeab0089a9236dfc6c684ea98f650647EntityRecord();
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile.AttrId = (long?) outParamo_ProofOfForeignResidence.ssRequisitionContractFile.ssId;
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile.AttrRequisitionId = (long?) outParamo_ProofOfForeignResidence.ssRequisitionContractFile.ssRequisitionId;
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile.AttrRequisitionFileId = (long?) outParamo_ProofOfForeignResidence.ssRequisitionContractFile.ssRequisitionFileId;
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile.AttrContractFileTypeId = (int?) outParamo_ProofOfForeignResidence.ssRequisitionContractFile.ssContractFileTypeId;
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile.AttrAmount = (decimal?) outParamo_ProofOfForeignResidence.ssRequisitionContractFile.ssAmount;
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile.AttrCurrencyId = outParamo_ProofOfForeignResidence.ssRequisitionContractFile.ssCurrencyId;
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile.AttrDepositTypeId = (int?) outParamo_ProofOfForeignResidence.ssRequisitionContractFile.ssDepositTypeId;
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile.AttrInsuranceTypeId = (int?) outParamo_ProofOfForeignResidence.ssRequisitionContractFile.ssInsuranceTypeId;
result.outParamo_ProofOfForeignResidence.AttrRequisitionContractFile.AttrAdvancePaymentTypeId = (int?) outParamo_ProofOfForeignResidence.ssRequisitionContractFile.ssAdvancePaymentTypeId;
// Write the needed fields of the record outParamo_ProofOfForeignResidence.ssRequisitionFile to the result.outParamo_ProofOfForeignResidence.AttrRequisitionFile
result.outParamo_ProofOfForeignResidence.AttrRequisitionFile = new ssConectaProveedores.RestRecords.RESTEN_4cce425e15647f937e21de4e52849889EntityRecord();
result.outParamo_ProofOfForeignResidence.AttrRequisitionFile.AttrId = (long?) outParamo_ProofOfForeignResidence.ssRequisitionFile.ssId;
result.outParamo_ProofOfForeignResidence.AttrRequisitionFile.AttrFilename = outParamo_ProofOfForeignResidence.ssRequisitionFile.ssFilename;
result.outParamo_ProofOfForeignResidence.AttrRequisitionFile.AttrVENDOR = outParamo_ProofOfForeignResidence.ssRequisitionFile.ssVENDOR;
result.outParamo_ProofOfForeignResidence.AttrRequisitionFile.AttrDOC_TYPE = outParamo_ProofOfForeignResidence.ssRequisitionFile.ssDOC_TYPE;
result.outParamo_ProofOfForeignResidence.AttrRequisitionFile.AttrSAP_OBJECT = outParamo_ProofOfForeignResidence.ssRequisitionFile.ssSAP_OBJECT;
result.outParamo_ProofOfForeignResidence.AttrRequisitionFile.AttrCreatedBy = outParamo_ProofOfForeignResidence.ssRequisitionFile.ssCreatedBy;
result.outParamo_ProofOfForeignResidence.AttrRequisitionFile.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_ProofOfForeignResidence.ssRequisitionFile.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_ProofOfForeignResidence.AttrRequisitionFile.AttrStorageId = (long?) outParamo_ProofOfForeignResidence.ssRequisitionFile.ssStorageId;
// Write the needed fields of the record outParamo_ProofOfForeignResidence.ssValid to the result.outParamo_ProofOfForeignResidence.AttrValid
result.outParamo_ProofOfForeignResidence.AttrValid = new ssConectaProveedores.RestRecords.RESTST_b453bea0930035904f55a74692afd3a8Structure();
result.outParamo_ProofOfForeignResidence.AttrValid.AttrIsValid = (bool?) outParamo_ProofOfForeignResidence.ssValid.ssIsValid;
result.outParamo_ProofOfForeignResidence.AttrValid.AttrValidationMessage = outParamo_ProofOfForeignResidence.ssValid.ssValidationMessage;
result.outParamo_ProofOfForeignResidence.AttrBinary = outParamo_ProofOfForeignResidence.ssBinary;
result.outParamo_ProofOfForeignResidence.AttrBigUploadfileId = (long?) outParamo_ProofOfForeignResidence.ssBigUploadfileId;
return result;
}


    public static ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Model ToModel(RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Outputs variables) {ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Model result = new ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Model();
result.outParamo_FinanceAuthorization = variables == null ? new ST_26b16bea631cbd94cf555acb5c7a4be3Structure() : ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.ToStructure(variables.outParamo_FinanceAuthorization);
result.outParamo_ProofOfForeignResidence = variables == null ? new ST_26b16bea631cbd94cf555acb5c7a4be3Structure() : ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.ToStructure(variables.outParamo_ProofOfForeignResidence);
return result;
}


    public static RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Outputs result = new RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetRequisitionFiles_Outputs();
result.outParamo_FinanceAuthorization = ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.FromStructure(screenModel.outParamo_FinanceAuthorization, conf);
result.outParamo_ProofOfForeignResidence = ssConectaProveedores.RestRecords.RESTST_26b16bea631cbd94cf555acb5c7a4be3Structure.FromStructure(screenModel.outParamo_ProofOfForeignResidence, conf);
return result;
}

}
