using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_d_InvoicePopups_Wb_PopupInvoiceAccountingImport_ActionImportAccounting_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("o_Output")]
public ssConectaProveedores.RestRecords.RESTST_046fb53ebbe142526d95e87ef1ae9711Structure outParamo_Output;
[JsonProperty("o_InvoiceAccounting")]
public ssConectaProveedores.RestRecords.RESTEN_b3917cbd7cc45d0b71b8ce3e028f14a3EntityRecord outParamo_InvoiceAccounting;
[JsonProperty("o_InvoiceAccountingEntries")]
public RestList<ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord> outParamo_InvoiceAccountingEntries;
[JsonProperty("o_InvoiceAccountingServices")]
public RestList<ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424> outParamo_InvoiceAccountingServices;


    public static RESTConectaProveedores_d_InvoicePopups_Wb_PopupInvoiceAccountingImport_ActionImportAccounting_Outputs FromOutputs(IBehaviorsConfiguration conf, ST_046fb53ebbe142526d95e87ef1ae9711Structure outParamo_Output, EN_b3917cbd7cc45d0b71b8ce3e028f14a3EntityRecord outParamo_InvoiceAccounting, RL_0704e14bc1b3305d76f59d709913c287 outParamo_InvoiceAccountingEntries, RL_d55212981ba3c49c0fb66324f6a1411a outParamo_InvoiceAccountingServices) {RESTConectaProveedores_d_InvoicePopups_Wb_PopupInvoiceAccountingImport_ActionImportAccounting_Outputs result = new RESTConectaProveedores_d_InvoicePopups_Wb_PopupInvoiceAccountingImport_ActionImportAccounting_Outputs();
conf.IncludeBinariesURL = false;
// Write the needed fields of the record outParamo_Output to the result.outParamo_Output
result.outParamo_Output = new ssConectaProveedores.RestRecords.RESTST_046fb53ebbe142526d95e87ef1ae9711Structure();
result.outParamo_Output.AttrIsSuccess = (bool?) outParamo_Output.ssIsSuccess;
result.outParamo_Output.AttrMessage = outParamo_Output.ssMessage;
// Write optimized result.outParamo_Output.AttrLines
result.outParamo_Output.AttrLines = (int?) 0;
// Write the needed fields of the record outParamo_InvoiceAccounting to the result.outParamo_InvoiceAccounting
result.outParamo_InvoiceAccounting = new ssConectaProveedores.RestRecords.RESTEN_b3917cbd7cc45d0b71b8ce3e028f14a3EntityRecord();
result.outParamo_InvoiceAccounting.AttrId = (long?) outParamo_InvoiceAccounting.ssId;
result.outParamo_InvoiceAccounting.AttrInvoiceId = (long?) outParamo_InvoiceAccounting.ssInvoiceId;
result.outParamo_InvoiceAccounting.AttrSupplierNumber = outParamo_InvoiceAccounting.ssSupplierNumber;
result.outParamo_InvoiceAccounting.AttrServiceTypeId = (long?) outParamo_InvoiceAccounting.ssServiceTypeId;
result.outParamo_InvoiceAccounting.AttrFreeText = outParamo_InvoiceAccounting.ssFreeText;
result.outParamo_InvoiceAccounting.AttrDivision = outParamo_InvoiceAccounting.ssDivision;
result.outParamo_InvoiceAccounting.AttrIvaAmount = (decimal?) outParamo_InvoiceAccounting.ssIvaAmount;
result.outParamo_InvoiceAccounting.AttrIva_Old = outParamo_InvoiceAccounting.ssIva_Old;
result.outParamo_InvoiceAccounting.AttrIvaIndicatorId = (long?) outParamo_InvoiceAccounting.ssIvaIndicatorId;
result.outParamo_InvoiceAccounting.AttrTotalAmount = (decimal?) outParamo_InvoiceAccounting.ssTotalAmount;
result.outParamo_InvoiceAccounting.AttrPaymentMethodId = (long?) outParamo_InvoiceAccounting.ssPaymentMethodId;
result.outParamo_InvoiceAccounting.AttrPaymentTermsId = (long?) outParamo_InvoiceAccounting.ssPaymentTermsId;
result.outParamo_InvoiceAccounting.AttrICMEIndicator = outParamo_InvoiceAccounting.ssICMEIndicator;
result.outParamo_InvoiceAccounting.AttrCreatedBy = outParamo_InvoiceAccounting.ssCreatedBy;
result.outParamo_InvoiceAccounting.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccounting.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_InvoiceAccounting.AttrSubmissionBy = outParamo_InvoiceAccounting.ssSubmissionBy;
result.outParamo_InvoiceAccounting.AttrSubmissionOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccounting.ssSubmissionOn, conf.DateTimeFormat);
result.outParamo_InvoiceAccounting.AttrServiceCalledBy = outParamo_InvoiceAccounting.ssServiceCalledBy;
result.outParamo_InvoiceAccounting.AttrServiceCalledOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccounting.ssServiceCalledOn, conf.DateTimeFormat);
result.outParamo_InvoiceAccounting.AttrBuyDocNumber = outParamo_InvoiceAccounting.ssBuyDocNumber;
result.outParamo_InvoiceAccounting.AttrBuyDocPosition = outParamo_InvoiceAccounting.ssBuyDocPosition;
// Write the needed fields of the list outParamo_InvoiceAccountingEntries to the result.outParamo_InvoiceAccountingEntries
ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord tmpoutParamo_InvoiceAccountingEntriesElement;
if(outParamo_InvoiceAccountingEntries.Empty) {
// Write the needed fields of the record outParamo_InvoiceAccountingEntries.CurrentRec to the tmpoutParamo_InvoiceAccountingEntriesElement
tmpoutParamo_InvoiceAccountingEntriesElement = new ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord();
tmpoutParamo_InvoiceAccountingEntriesElement.AttrId = (long?) outParamo_InvoiceAccountingEntries.CurrentRec.ssId;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrInvoiceId = (long?) outParamo_InvoiceAccountingEntries.CurrentRec.ssInvoiceId;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrControldedocumento = (int?) outParamo_InvoiceAccountingEntries.CurrentRec.ssControldedocumento;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrFechadedocumento = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_InvoiceAccountingEntries.CurrentRec.ssFechadedocumento);
tmpoutParamo_InvoiceAccountingEntriesElement.AttrFechadecontabilizacion = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_InvoiceAccountingEntries.CurrentRec.ssFechadecontabilizacion);
tmpoutParamo_InvoiceAccountingEntriesElement.AttrClasededocumento = outParamo_InvoiceAccountingEntries.CurrentRec.ssClasededocumento;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrSociedad = outParamo_InvoiceAccountingEntries.CurrentRec.ssSociedad;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrMoneda = outParamo_InvoiceAccountingEntries.CurrentRec.ssMoneda;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrTipodeCambio = outParamo_InvoiceAccountingEntries.CurrentRec.ssTipodeCambio;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrFechadeConversion = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_InvoiceAccountingEntries.CurrentRec.ssFechadeConversion);
tmpoutParamo_InvoiceAccountingEntriesElement.AttrNumerodeDoc_DeReferencia = outParamo_InvoiceAccountingEntries.CurrentRec.ssNumerodeDoc_DeReferencia;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrTextodeCabeceradeDocumento = outParamo_InvoiceAccountingEntries.CurrentRec.ssTextodeCabeceradeDocumento;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrClaveContabilizacion = (int?) outParamo_InvoiceAccountingEntries.CurrentRec.ssClaveContabilizacion;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCuentadeMayor = outParamo_InvoiceAccountingEntries.CurrentRec.ssCuentadeMayor;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrIndicadorICME = outParamo_InvoiceAccountingEntries.CurrentRec.ssIndicadorICME;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrImporteenmonedadeldocto = (decimal?) outParamo_InvoiceAccountingEntries.CurrentRec.ssImporteenmonedadeldocto;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCalcularimpuestos = outParamo_InvoiceAccountingEntries.CurrentRec.ssCalcularimpuestos;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrIndicadordeIVA = outParamo_InvoiceAccountingEntries.CurrentRec.ssIndicadordeIVA;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrDivision = outParamo_InvoiceAccountingEntries.CurrentRec.ssDivision;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCondicionesdepago = outParamo_InvoiceAccountingEntries.CurrentRec.ssCondicionesdepago;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrFechabase = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_InvoiceAccountingEntries.CurrentRec.ssFechabase);
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCentrodecostos = outParamo_InvoiceAccountingEntries.CurrentRec.ssCentrodecostos;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCentrodebeneficio = outParamo_InvoiceAccountingEntries.CurrentRec.ssCentrodebeneficio;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrNumerodeasignacion = outParamo_InvoiceAccountingEntries.CurrentRec.ssNumerodeasignacion;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrTexto = outParamo_InvoiceAccountingEntries.CurrentRec.ssTexto;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrF_vencimiento = outParamo_InvoiceAccountingEntries.CurrentRec.ssF_vencimiento;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrF_valor = outParamo_InvoiceAccountingEntries.CurrentRec.ssF_valor;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrV_pago = outParamo_InvoiceAccountingEntries.CurrentRec.ssV_pago;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrNombre = outParamo_InvoiceAccountingEntries.CurrentRec.ssNombre;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrPoblacion = outParamo_InvoiceAccountingEntries.CurrentRec.ssPoblacion;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrClavebanco = outParamo_InvoiceAccountingEntries.CurrentRec.ssClavebanco;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCta_bancaria = outParamo_InvoiceAccountingEntries.CurrentRec.ssCta_bancaria;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCuentaalternativa = outParamo_InvoiceAccountingEntries.CurrentRec.ssCuentaalternativa;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCreatedBy = outParamo_InvoiceAccountingEntries.CurrentRec.ssCreatedBy;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingEntries.CurrentRec.ssCreatedOn, conf.DateTimeFormat);
result.outParamo_InvoiceAccountingEntries = new RestList<ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord>(new ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord[] {}, tmpoutParamo_InvoiceAccountingEntriesElement);
} else {
List<ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord>
 tmpoutParamo_InvoiceAccountingEntries1List = new List<ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord>
();
try {outParamo_InvoiceAccountingEntries.StartIteration();
while (!(outParamo_InvoiceAccountingEntries.Eof)) {
// Write the needed fields of the record outParamo_InvoiceAccountingEntries.CurrentRec to the tmpoutParamo_InvoiceAccountingEntriesElement
tmpoutParamo_InvoiceAccountingEntriesElement = new ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord();
tmpoutParamo_InvoiceAccountingEntriesElement.AttrId = (long?) outParamo_InvoiceAccountingEntries.CurrentRec.ssId;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrInvoiceId = (long?) outParamo_InvoiceAccountingEntries.CurrentRec.ssInvoiceId;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrControldedocumento = (int?) outParamo_InvoiceAccountingEntries.CurrentRec.ssControldedocumento;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrFechadedocumento = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_InvoiceAccountingEntries.CurrentRec.ssFechadedocumento);
tmpoutParamo_InvoiceAccountingEntriesElement.AttrFechadecontabilizacion = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_InvoiceAccountingEntries.CurrentRec.ssFechadecontabilizacion);
tmpoutParamo_InvoiceAccountingEntriesElement.AttrClasededocumento = outParamo_InvoiceAccountingEntries.CurrentRec.ssClasededocumento;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrSociedad = outParamo_InvoiceAccountingEntries.CurrentRec.ssSociedad;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrMoneda = outParamo_InvoiceAccountingEntries.CurrentRec.ssMoneda;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrTipodeCambio = outParamo_InvoiceAccountingEntries.CurrentRec.ssTipodeCambio;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrFechadeConversion = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_InvoiceAccountingEntries.CurrentRec.ssFechadeConversion);
tmpoutParamo_InvoiceAccountingEntriesElement.AttrNumerodeDoc_DeReferencia = outParamo_InvoiceAccountingEntries.CurrentRec.ssNumerodeDoc_DeReferencia;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrTextodeCabeceradeDocumento = outParamo_InvoiceAccountingEntries.CurrentRec.ssTextodeCabeceradeDocumento;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrClaveContabilizacion = (int?) outParamo_InvoiceAccountingEntries.CurrentRec.ssClaveContabilizacion;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCuentadeMayor = outParamo_InvoiceAccountingEntries.CurrentRec.ssCuentadeMayor;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrIndicadorICME = outParamo_InvoiceAccountingEntries.CurrentRec.ssIndicadorICME;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrImporteenmonedadeldocto = (decimal?) outParamo_InvoiceAccountingEntries.CurrentRec.ssImporteenmonedadeldocto;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCalcularimpuestos = outParamo_InvoiceAccountingEntries.CurrentRec.ssCalcularimpuestos;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrIndicadordeIVA = outParamo_InvoiceAccountingEntries.CurrentRec.ssIndicadordeIVA;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrDivision = outParamo_InvoiceAccountingEntries.CurrentRec.ssDivision;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCondicionesdepago = outParamo_InvoiceAccountingEntries.CurrentRec.ssCondicionesdepago;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrFechabase = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateToText(outParamo_InvoiceAccountingEntries.CurrentRec.ssFechabase);
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCentrodecostos = outParamo_InvoiceAccountingEntries.CurrentRec.ssCentrodecostos;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCentrodebeneficio = outParamo_InvoiceAccountingEntries.CurrentRec.ssCentrodebeneficio;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrNumerodeasignacion = outParamo_InvoiceAccountingEntries.CurrentRec.ssNumerodeasignacion;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrTexto = outParamo_InvoiceAccountingEntries.CurrentRec.ssTexto;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrF_vencimiento = outParamo_InvoiceAccountingEntries.CurrentRec.ssF_vencimiento;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrF_valor = outParamo_InvoiceAccountingEntries.CurrentRec.ssF_valor;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrV_pago = outParamo_InvoiceAccountingEntries.CurrentRec.ssV_pago;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrNombre = outParamo_InvoiceAccountingEntries.CurrentRec.ssNombre;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrPoblacion = outParamo_InvoiceAccountingEntries.CurrentRec.ssPoblacion;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrClavebanco = outParamo_InvoiceAccountingEntries.CurrentRec.ssClavebanco;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCta_bancaria = outParamo_InvoiceAccountingEntries.CurrentRec.ssCta_bancaria;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCuentaalternativa = outParamo_InvoiceAccountingEntries.CurrentRec.ssCuentaalternativa;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCreatedBy = outParamo_InvoiceAccountingEntries.CurrentRec.ssCreatedBy;
tmpoutParamo_InvoiceAccountingEntriesElement.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingEntries.CurrentRec.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingEntries1List.Add(tmpoutParamo_InvoiceAccountingEntriesElement);
outParamo_InvoiceAccountingEntries.Advance();
}

} finally {
outParamo_InvoiceAccountingEntries.EndIteration();
}

result.outParamo_InvoiceAccountingEntries = new RestList<ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord>(tmpoutParamo_InvoiceAccountingEntries1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTEN_66fb76d3fab58a693a3c750c022bd4efEntityRecord));
}

// Write the needed fields of the list outParamo_InvoiceAccountingServices to the result.outParamo_InvoiceAccountingServices
ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424 tmpoutParamo_InvoiceAccountingServicesElement;
if(outParamo_InvoiceAccountingServices.Empty) {
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec to the tmpoutParamo_InvoiceAccountingServicesElement
tmpoutParamo_InvoiceAccountingServicesElement = new ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424();
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices to the tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices = new ssConectaProveedores.RestRecords.RESTEN_103cfe3736a71d97f9a0699797cf8ac2EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrInvoiceAccountingId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssInvoiceAccountingId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrServiceTypeId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssServiceTypeId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrAccount = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssAccount;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrCostCenterId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssCostCenterId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrCeBeCostCenterId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssCeBeCostCenterId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrAmount = (decimal?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssAmount;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrIVA_Old = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssIVA_Old;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrIVAIndicatorId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssIVAIndicatorId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrBuyDocNumber = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssBuyDocNumber;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrBuyDocPosition = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssBuyDocPosition;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrFreeText = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssFreeText;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrDivision = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssDivision;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrICME = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssICME;
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType to the tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType = new ssConectaProveedores.RestRecords.RESTEN_7d4692fd3a99ff3b1c123c777f28bd70EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrCC = outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssCC;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrDescription = outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssDescription;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrIsActive = (bool?) outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssIsActive;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrCreatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssCreatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrUpdatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssUpdatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrUpdatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssUpdatedOn, conf.DateTimeFormat);
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator to the tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator = new ssConectaProveedores.RestRecords.RESTEN_efc751d189a1545503ba31ced5225e86EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrDescription = outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssDescription;
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrExternalId = outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssExternalId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrCreatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssCreatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrUpdatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssUpdatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrUpdatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssUpdatedBy;
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP to the tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP = new ssConectaProveedores.RestRecords.RESTEN_a1a752e04a72b49d9ac24eb8f53d0c86EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrRegionId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssRegionId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCompanyId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCompanyId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrSoc_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssSoc_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrDiv_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssDiv_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrArea = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssArea;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCe_coste = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCe_coste;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCeBe = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCeBe;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrDenominacion = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssDenominacion;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrDescripcion = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssDescripcion;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrResponsable = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssResponsable;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCeCo = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCeCo;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCostesprim_reales_Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCostesprim_reales_Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCostessecund_reales_Ind_debl = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCostessecund_reales_Ind_debl;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrIngresosreales_Ind_debloqueo = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssIngresosreales_Ind_debloqueo;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrActualiz_comprom__Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssActualiz_comprom__Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCostesprimariosplan_Ind_debl = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCostesprimariosplan_Ind_debl;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCostessecund_plan_Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCostessecund_plan_Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrIngresosplan_Ind_debloqueo_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssIngresosplan_Ind_debloqueo_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrAutor = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssAutor;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCreatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCreatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrUpdatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssUpdatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrUpdatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssUpdatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrIsActive = (bool?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssIsActive;
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP to the tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP = new ssConectaProveedores.RestRecords.RESTEN_a1a752e04a72b49d9ac24eb8f53d0c86EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrRegionId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssRegionId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCompanyId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCompanyId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrSoc_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssSoc_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrDiv_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssDiv_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrArea = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssArea;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCe_coste = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCe_coste;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCeBe = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCeBe;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrDenominacion = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssDenominacion;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrDescripcion = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssDescripcion;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrResponsable = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssResponsable;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCeCo = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCeCo;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCostesprim_reales_Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCostesprim_reales_Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCostessecund_reales_Ind_debl = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCostessecund_reales_Ind_debl;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrIngresosreales_Ind_debloqueo = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssIngresosreales_Ind_debloqueo;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrActualiz_comprom__Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssActualiz_comprom__Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCostesprimariosplan_Ind_debl = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCostesprimariosplan_Ind_debl;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCostessecund_plan_Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCostessecund_plan_Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrIngresosplan_Ind_debloqueo_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssIngresosplan_Ind_debloqueo_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrAutor = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssAutor;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCreatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCreatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrUpdatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssUpdatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrUpdatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssUpdatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrIsActive = (bool?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssIsActive;
result.outParamo_InvoiceAccountingServices = new RestList<ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424>(new ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424[] {}, tmpoutParamo_InvoiceAccountingServicesElement);
} else {
List<ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424>
 tmpoutParamo_InvoiceAccountingServices1List = new List<ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424>
();
try {outParamo_InvoiceAccountingServices.StartIteration();
while (!(outParamo_InvoiceAccountingServices.Eof)) {
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec to the tmpoutParamo_InvoiceAccountingServicesElement
tmpoutParamo_InvoiceAccountingServicesElement = new ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424();
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices to the tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices = new ssConectaProveedores.RestRecords.RESTEN_103cfe3736a71d97f9a0699797cf8ac2EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrInvoiceAccountingId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssInvoiceAccountingId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrServiceTypeId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssServiceTypeId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrAccount = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssAccount;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrCostCenterId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssCostCenterId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrCeBeCostCenterId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssCeBeCostCenterId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrAmount = (decimal?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssAmount;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrIVA_Old = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssIVA_Old;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrIVAIndicatorId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssIVAIndicatorId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrBuyDocNumber = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssBuyDocNumber;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrBuyDocPosition = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssBuyDocPosition;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrFreeText = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssFreeText;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrDivision = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssDivision;
tmpoutParamo_InvoiceAccountingServicesElement.AttrInvoiceAccountingServices.AttrICME = outParamo_InvoiceAccountingServices.CurrentRec.ssENInvoiceAccountingServices.ssICME;
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType to the tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType = new ssConectaProveedores.RestRecords.RESTEN_7d4692fd3a99ff3b1c123c777f28bd70EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrCC = outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssCC;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrDescription = outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssDescription;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrIsActive = (bool?) outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssIsActive;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrCreatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssCreatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrUpdatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssUpdatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrAccountingAccounts_ServiceType.AttrUpdatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENAccountingAccounts_ServiceType.ssUpdatedOn, conf.DateTimeFormat);
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator to the tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator = new ssConectaProveedores.RestRecords.RESTEN_efc751d189a1545503ba31ced5225e86EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrDescription = outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssDescription;
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrExternalId = outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssExternalId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrCreatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssCreatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrUpdatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssUpdatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrTaxIndicator.AttrUpdatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENTaxIndicator.ssUpdatedBy;
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP to the tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP = new ssConectaProveedores.RestRecords.RESTEN_a1a752e04a72b49d9ac24eb8f53d0c86EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrRegionId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssRegionId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCompanyId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCompanyId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrSoc_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssSoc_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrDiv_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssDiv_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrArea = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssArea;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCe_coste = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCe_coste;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCeBe = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCeBe;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrDenominacion = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssDenominacion;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrDescripcion = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssDescripcion;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrResponsable = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssResponsable;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCeCo = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCeCo;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCostesprim_reales_Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCostesprim_reales_Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCostessecund_reales_Ind_debl = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCostessecund_reales_Ind_debl;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrIngresosreales_Ind_debloqueo = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssIngresosreales_Ind_debloqueo;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrActualiz_comprom__Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssActualiz_comprom__Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCostesprimariosplan_Ind_debl = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCostesprimariosplan_Ind_debl;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCostessecund_plan_Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCostessecund_plan_Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrIngresosplan_Ind_debloqueo_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssIngresosplan_Ind_debloqueo_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrAutor = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssAutor;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrCreatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssCreatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrUpdatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssUpdatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrUpdatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssUpdatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCeBeCostCenterSAP.AttrIsActive = (bool?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCeBeCostCenterSAP.ssIsActive;
// Write the needed fields of the record outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP to the tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP = new ssConectaProveedores.RestRecords.RESTEN_a1a752e04a72b49d9ac24eb8f53d0c86EntityRecord();
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrRegionId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssRegionId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCompanyId = (long?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCompanyId;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrSoc_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssSoc_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrDiv_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssDiv_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrArea = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssArea;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCe_coste = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCe_coste;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCeBe = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCeBe;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrDenominacion = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssDenominacion;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrDescripcion = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssDescripcion;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrResponsable = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssResponsable;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCeCo = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCeCo;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCostesprim_reales_Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCostesprim_reales_Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCostessecund_reales_Ind_debl = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCostessecund_reales_Ind_debl;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrIngresosreales_Ind_debloqueo = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssIngresosreales_Ind_debloqueo;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrActualiz_comprom__Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssActualiz_comprom__Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCostesprimariosplan_Ind_debl = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCostesprimariosplan_Ind_debl;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCostessecund_plan_Ind_debloq = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCostessecund_plan_Ind_debloq;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrIngresosplan_Ind_debloqueo_ = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssIngresosplan_Ind_debloqueo_;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrAutor = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssAutor;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCreatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCreatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrCreatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssCreatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrUpdatedOn = OutSystems.RESTService.Runtime.Abstractions.Conversions.DateTimeToRestType(outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssUpdatedOn, conf.DateTimeFormat);
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrUpdatedBy = outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssUpdatedBy;
tmpoutParamo_InvoiceAccountingServicesElement.AttrCostCenterSAP.AttrIsActive = (bool?) outParamo_InvoiceAccountingServices.CurrentRec.ssENCostCenterSAP.ssIsActive;
tmpoutParamo_InvoiceAccountingServices1List.Add(tmpoutParamo_InvoiceAccountingServicesElement);
outParamo_InvoiceAccountingServices.Advance();
}

} finally {
outParamo_InvoiceAccountingServices.EndIteration();
}

result.outParamo_InvoiceAccountingServices = new RestList<ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424>(tmpoutParamo_InvoiceAccountingServices1List.ToArray(), default(ssConectaProveedores.RestRecords.RESTRC_3a3d5d4cc50f8572263073b452541424));
}

return result;
}


    

    
}
