using OutSystems.RESTService.Runtime.Abstractions.Behaviors;
using OutSystems.RESTService.Runtime.Core.Controllers;
using OutSystems.RESTService.Runtime.Core.Controllers.ScreenServices;

namespace ssConectaProveedores.ScreenServices;

public class RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Outputs : ScreenServicesApiController.Payload.IDataPayload {

    [JsonProperty("IsCorporativo")]
public bool? outParamIsCorporativo;


    public static RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Outputs FromOutputs(IBehaviorsConfiguration conf, bool outParamIsCorporativo) {RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Outputs result = new RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Outputs();
result.outParamIsCorporativo = (bool?) outParamIsCorporativo;
return result;
}


    public static ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Model ToModel(RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Outputs variables) {ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Model result = new ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Model();
result.outParamIsCorporativo = variables == null || variables.outParamIsCorporativo == null ? false : variables.outParamIsCorporativo.Value;
return result;
}


    public static RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Outputs FromModel(IBehaviorsConfiguration conf, ConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Model screenModel) {if((screenModel == null)) {
return null;
}

RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Outputs result = new RESTConectaProveedores_c_Requisitions_RequisitionDetail_DataActionGetShowSelectReqPopup_Outputs();
result.outParamIsCorporativo = (bool?) screenModel.outParamIsCorporativo;
return result;
}

}
