using System.Diagnostics;
namespace ssConectaProveedores {

public sealed partial class ENInvoiceAccountingEntriesEntity {
private static readonly ActivitySource activitySource = new(typeof(ENInvoiceAccountingEntriesEntity).Namespace);
private static System.Collections.Generic.Dictionary<string,string> _entityAttributes;
private static System.Collections.Generic.Dictionary<string,string> EntityAttributes => _entityAttributes ??= InitializeEntityAttributes();

private static System.Collections.Generic.Dictionary<string,string> InitializeEntityAttributes() {
return new System.Collections.Generic.Dictionary<string,string> {
{"id", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Id, "id") ?? "id"},
{"invoiceid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@InvoiceId, "invoiceid") ?? "invoiceid"},
{"controldedocumento", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Controldedocumento, "controldedocumento") ?? "controldedocumento"},
{"fechadedocumento", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Fechadedocumento, "fechadedocumento") ?? "fechadedocumento"},
{"fechadecontabilizacion", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Fechadecontabilizacion, "fechadecontabilizacion") ?? "fechadecontabilizacion"},
{"clasededocumento", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Clasededocumento, "clasededocumento") ?? "clasededocumento"},
{"sociedad", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Sociedad, "sociedad") ?? "sociedad"},
{"moneda", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Moneda, "moneda") ?? "moneda"},
{"tipodecambio", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@TipodeCambio, "tipodecambio") ?? "tipodecambio"},
{"fechadeconversion", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@FechadeConversion, "fechadeconversion") ?? "fechadeconversion"},
{"numerodedoc_dereferencia", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@NumerodeDoc_DeReferencia, "numerodedoc_dereferencia") ?? "numerodedoc_dereferencia"},
{"textodecabeceradedocumento", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@TextodeCabeceradeDocumento, "textodecabeceradedocumento") ?? "textodecabeceradedocumento"},
{"clavecontabilizacion", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@ClaveContabilizacion, "clavecontabilizacion") ?? "clavecontabilizacion"},
{"cuentademayor", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@CuentadeMayor, "cuentademayor") ?? "cuentademayor"},
{"indicadoricme", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@IndicadorICME, "indicadoricme") ?? "indicadoricme"},
{"importeenmonedadeldocto", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Importeenmonedadeldocto, "importeenmonedadeldocto") ?? "importeenmonedadeldocto"},
{"calcularimpuestos", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Calcularimpuestos, "calcularimpuestos") ?? "calcularimpuestos"},
{"indicadordeiva", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@IndicadordeIVA, "indicadordeiva") ?? "indicadordeiva"},
{"division", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Division, "division") ?? "division"},
{"condicionesdepago", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Condicionesdepago, "condicionesdepago") ?? "condicionesdepago"},
{"fechabase", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Fechabase, "fechabase") ?? "fechabase"},
{"centrodecostos", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Centrodecostos, "centrodecostos") ?? "centrodecostos"},
{"centrodebeneficio", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Centrodebeneficio, "centrodebeneficio") ?? "centrodebeneficio"},
{"numerodeasignacion", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Numerodeasignacion, "numerodeasignacion") ?? "numerodeasignacion"},
{"texto", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Texto, "texto") ?? "texto"},
{"f_vencimiento", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@F_vencimiento, "f_vencimiento") ?? "f_vencimiento"},
{"f_valor", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@F_valor, "f_valor") ?? "f_valor"},
{"v_pago", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@V_pago, "v_pago") ?? "v_pago"},
{"nombre", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Nombre, "nombre") ?? "nombre"},
{"poblacion", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Poblacion, "poblacion") ?? "poblacion"},
{"clavebanco", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Clavebanco, "clavebanco") ?? "clavebanco"},
{"cta_bancaria", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Cta_bancaria, "cta_bancaria") ?? "cta_bancaria"},
{"cuentaalternativa", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@Cuentaalternativa, "cuentaalternativa") ?? "cuentaalternativa"},
{"createdby", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@CreatedBy, "createdby") ?? "createdby"},
{"createdon", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, _EntityKeyConstants._ConectaProveedoresEntityKeys._InvoiceAccountingEntriesAttributeKeys.@CreatedOn, "createdon") ?? "createdon"}
};
}
public static System.Collections.Generic.Dictionary<string,string> AttributesToDatabaseNamesMap() {
return EntityAttributes;
}
public static string AttributeDatabaseName(string attributeName) {
string databaseName;
EntityAttributes.TryGetValue(attributeName, out databaseName);
return databaseName;
}
public static string LocalViewName(string locale) {
return ViewName(locale);
}
public static string ViewName(string locale) {
return BaseAppUtils.EscapeAndQualifySqlIdentifier(DatabaseAccess.ForRuntimeDatabase, TableDetailsServiceAccessor.Instance?.GetValidatedTableName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@InvoiceAccountingEntries, "invoi_u8aqr95gpfercbrdfg0m0sk6"));
}
} // ENInvoiceAccountingEntriesEntity

}

