using System.Diagnostics;
namespace ssConectaProveedores {

public sealed partial class ENApprovalStatusEntity {
private static readonly ActivitySource activitySource = new(typeof(ENApprovalStatusEntity).Namespace);
private static System.Collections.Generic.Dictionary<string,string> _entityAttributes;
private static System.Collections.Generic.Dictionary<string,string> EntityAttributes => _entityAttributes ??= InitializeEntityAttributes();

private static System.Collections.Generic.Dictionary<string,string> InitializeEntityAttributes() {
return new System.Collections.Generic.Dictionary<string,string> {
{"id", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@Id, "id") ?? "id"},
{"label", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@Label, "label") ?? "label"},
{"class", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@Class, "class") ?? "class"},
{"order", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@Order, "order") ?? "order"},
{"is_active", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@Is_Active, "is_active") ?? "is_active"},
{"iscya", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@IsCyA, "iscya") ?? "iscya"},
{"iscyaapproval", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@IsCyAApproval, "iscyaapproval") ?? "iscyaapproval"},
{"isreq", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@IsReq, "isreq") ?? "isreq"},
{"isinv", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@IsInv, "isinv") ?? "isinv"},
{"labeles", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, _EntityKeyConstants._ConectaProveedoresEntityKeys._ApprovalStatusAttributeKeys.@LabelES, "labeles") ?? "labeles"}
};
}
public static System.Collections.Generic.Dictionary<string,string> AttributesToDatabaseNamesMap() {
return EntityAttributes;
}
public static string AttributeDatabaseName(string attributeName) {
string databaseName;
EntityAttributes.TryGetValue(attributeName, out databaseName);
return databaseName;
}
public static string LocalViewName(string locale) {
return ViewName(locale);
}
public static string ViewName(string locale) {
switch (locale == null ? string.Empty : locale.ToLowerInvariant()) {
case "es-mx": return BaseAppUtils.EscapeAndQualifySqlIdentifier(DatabaseAccess.ForRuntimeDatabase, TableDetailsServiceAccessor.Instance?.GetValidatedTableName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, "appro_u8aqr95gpfe_xyq7wncm7fl5") + "_ml_es_MX");
case "en-us": return BaseAppUtils.EscapeAndQualifySqlIdentifier(DatabaseAccess.ForRuntimeDatabase, TableDetailsServiceAccessor.Instance?.GetValidatedTableName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, "appro_u8aqr95gpfe_xyq7wncm7fl5") + "_ml_en_US");
default :
int pos;
if (!string.IsNullOrEmpty(locale) && ((pos = locale.IndexOf('-')) > 0))
return ViewName(locale.Substring(0, pos));
else
return BaseAppUtils.EscapeAndQualifySqlIdentifier(DatabaseAccess.ForRuntimeDatabase, TableDetailsServiceAccessor.Instance?.GetValidatedTableName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@ApprovalStatus, "appro_u8aqr95gpfe_xyq7wncm7fl5"));
}
}
} // ENApprovalStatusEntity
partial class ENApprovalStatusEntity : InMemoryStaticEntityRuntime<EN_e97ac0d21205ff90ab42100bba6097baEntityRecord, int> {
    

    private static ENApprovalStatusEntity instance = new();
    public static ENApprovalStatusEntity GetInstance() => instance;

    public static EN_e97ac0d21205ff90ab42100bba6097baEntityRecord GetRecordById(int id) {
return instance.GetRecord(id);
}

    public static EN_e97ac0d21205ff90ab42100bba6097baEntityRecord GetRecordByKey(ObjectKey key) {
if(!instance.TryGetRecordIdentifierByKey(key, out var meta)) {
throw DatabaseErrorsHelper.StaticEntityRecordMetadataNotFound(ViewName(string.Empty), ObjectKeyUtils.DatabaseValue(key));
}
return instance.GetRecord(meta);
}


    protected override Dictionary<ObjectKey, int> RecordKeyToIdMap { get; } = new() {
        { ObjectKey.Parse("rm4bAZ7dOEqgMcZKM9wLxg"), 3 },
{ ObjectKey.Parse("85A3EYx6OkWpq0CAyB7XJw"), 23 },
{ ObjectKey.Parse("WSrbHwGzvEKPytCj7doVWw"), 6 },
{ ObjectKey.Parse("RvhtMOVzUke_jX9z3pm9HA"), 28 },
{ ObjectKey.Parse("EW9OOAC7ZEm3iGeypPwFAg"), 26 },
{ ObjectKey.Parse("bxcfUQnAU0CWvUsA+ZfAjw"), 24 },
{ ObjectKey.Parse("D2_uWT_NNEy5Fa5VMXMLBw"), 21 },
{ ObjectKey.Parse("BjgcXy0kFU+8e5Ko3emFig"), 22 },
{ ObjectKey.Parse("w+wMayzP1kit5Zcgfd05+g"), 27 },
{ ObjectKey.Parse("2bH5k51Eqk+iM0PUO3cbyg"), 25 },
{ ObjectKey.Parse("YBJlnXS8SkKRSq9aruxhkg"), 8 },
{ ObjectKey.Parse("I4VnodzG6ke+WTu4gjHzUQ"), 4 },
{ ObjectKey.Parse("bkD8ux0JT02InXZZfkOUsA"), 7 },
{ ObjectKey.Parse("fEmjvBqEH0eHrf5_YVeo0g"), 10 },
{ ObjectKey.Parse("rkrV30n0cEiW8dttOKG0gw"), 2 },
{ ObjectKey.Parse("A8ye9hhImUaVe0wa+Rtbjg"), 9 },

    };

    protected override Dictionary<int, EN_e97ac0d21205ff90ab42100bba6097baEntityRecord> RecordIdToRecordMap { get; } = new() {
        {3, new() {
ssId = 3,
ssLabel = "Rejected",
ssClass = "rejected",
ssOrder = 8,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Rechazado",
}},
{23, new() {
ssId = 23,
ssLabel = "Assigned",
ssClass = "submitted",
ssOrder = 11,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = true,
ssLabelES = "Asignado",
}},
{6, new() {
ssId = 6,
ssLabel = "Paid",
ssClass = "paid",
ssOrder = 98,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Pagado",
}},
{28, new() {
ssId = 28,
ssLabel = "Evidence Review",
ssClass = "modify",
ssOrder = 6,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Revisión de Evidencia",
}},
{26, new() {
ssId = 26,
ssLabel = "Complemented",
ssClass = "approved",
ssOrder = 10,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Complementado",
}},
{24, new() {
ssId = 24,
ssLabel = "To Complement",
ssClass = "inapproval",
ssOrder = 3,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Para complementar",
}},
{21, new() {
ssId = 21,
ssLabel = "Not Approved",
ssClass = "inapproval",
ssOrder = 1,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = true,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Por Aprobar",
}},
{22, new() {
ssId = 22,
ssLabel = "To Assign",
ssClass = "saved",
ssOrder = 2,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = true,
ssLabelES = "Por Asignar",
}},
{27, new() {
ssId = 27,
ssLabel = "Evidence Requested",
ssClass = "modify",
ssOrder = 5,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Evidencia Solicitada",
}},
{25, new() {
ssId = 25,
ssLabel = "In Information Completion",
ssClass = "inapproval",
ssOrder = 4,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "En complemento de información",
}},
{8, new() {
ssId = 8,
ssLabel = "Canceled",
ssClass = "canceled",
ssOrder = 96,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Cancelado",
}},
{4, new() {
ssId = 4,
ssLabel = "ErrorAPI",
ssClass = "errorAPI",
ssOrder = 95,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Error API",
}},
{7, new() {
ssId = 7,
ssLabel = "Not Paid",
ssClass = "notpaid",
ssOrder = 97,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "No Pagado",
}},
{10, new() {
ssId = 10,
ssLabel = "Pending",
ssClass = "pending",
ssOrder = 99,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Pendiente",
}},
{2, new() {
ssId = 2,
ssLabel = "Approved",
ssClass = "approved",
ssOrder = 7,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = true,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Aprobado",
}},
{9, new() {
ssId = 9,
ssLabel = "Request to Modify",
ssClass = "modify",
ssOrder = 9,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Por Modificar",
}},

    };

    protected override Dictionary<string, Dictionary<int, EN_e97ac0d21205ff90ab42100bba6097baEntityRecord>> LocaleToRecordIdMap { get; } = new() {
        {"es-MX", new() {
{3, new() {
ssId = 3,
ssLabel = "Rechazado",
ssClass = "rejected",
ssOrder = 8,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Rechazado",
}},
{23, new() {
ssId = 23,
ssLabel = "Asignado",
ssClass = "submitted",
ssOrder = 11,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = true,
ssLabelES = "Asignado",
}},
{6, new() {
ssId = 6,
ssLabel = "Pagado",
ssClass = "paid",
ssOrder = 98,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Pagado",
}},
{28, new() {
ssId = 28,
ssLabel = "Revisión de Evidencia",
ssClass = "modify",
ssOrder = 6,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Revisión de Evidencia",
}},
{26, new() {
ssId = 26,
ssLabel = "Complementado",
ssClass = "approved",
ssOrder = 10,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Complementado",
}},
{24, new() {
ssId = 24,
ssLabel = "Para complementar",
ssClass = "inapproval",
ssOrder = 3,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Para complementar",
}},
{21, new() {
ssId = 21,
ssLabel = "Por Aprobar",
ssClass = "inapproval",
ssOrder = 1,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = true,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Por Aprobar",
}},
{22, new() {
ssId = 22,
ssLabel = "Por Asignar",
ssClass = "saved",
ssOrder = 2,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = true,
ssLabelES = "Por Asignar",
}},
{27, new() {
ssId = 27,
ssLabel = "Evidencia Solicitada",
ssClass = "modify",
ssOrder = 5,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Evidencia Solicitada",
}},
{25, new() {
ssId = 25,
ssLabel = "En complemento de información",
ssClass = "inapproval",
ssOrder = 4,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "En complemento de información",
}},
{8, new() {
ssId = 8,
ssLabel = "Cancelado",
ssClass = "canceled",
ssOrder = 96,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Cancelado",
}},
{4, new() {
ssId = 4,
ssLabel = "Error API",
ssClass = "errorAPI",
ssOrder = 95,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Error API",
}},
{7, new() {
ssId = 7,
ssLabel = "No Pagado",
ssClass = "notpaid",
ssOrder = 97,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "No Pagado",
}},
{10, new() {
ssId = 10,
ssLabel = "Pendiente",
ssClass = "pending",
ssOrder = 99,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Pendiente",
}},
{2, new() {
ssId = 2,
ssLabel = "Aprobado",
ssClass = "approved",
ssOrder = 7,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = true,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Aprobado",
}},
{9, new() {
ssId = 9,
ssLabel = "Por Modificar",
ssClass = "modify",
ssOrder = 9,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Por Modificar",
}},
}},
{"en-US", new() {
{3, new() {
ssId = 3,
ssLabel = "Rechazado",
ssClass = "rejected",
ssOrder = 8,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Rechazado",
}},
{23, new() {
ssId = 23,
ssLabel = "Assigned",
ssClass = "submitted",
ssOrder = 11,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = true,
ssLabelES = "Asignado",
}},
{6, new() {
ssId = 6,
ssLabel = "Paid",
ssClass = "paid",
ssOrder = 98,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Pagado",
}},
{28, new() {
ssId = 28,
ssLabel = "Evidence Review",
ssClass = "modify",
ssOrder = 6,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Revisión de Evidencia",
}},
{26, new() {
ssId = 26,
ssLabel = "Complemented",
ssClass = "approved",
ssOrder = 10,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Complementado",
}},
{24, new() {
ssId = 24,
ssLabel = "To Complement",
ssClass = "inapproval",
ssOrder = 3,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Para complementar",
}},
{21, new() {
ssId = 21,
ssLabel = "Not Approved",
ssClass = "inapproval",
ssOrder = 1,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = true,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Por Aprobar",
}},
{22, new() {
ssId = 22,
ssLabel = "To Assign",
ssClass = "saved",
ssOrder = 2,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = true,
ssLabelES = "Por Asignar",
}},
{27, new() {
ssId = 27,
ssLabel = "Evidence Requested",
ssClass = "modify",
ssOrder = 5,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Evidencia Solicitada",
}},
{25, new() {
ssId = 25,
ssLabel = "In Information Completion",
ssClass = "inapproval",
ssOrder = 4,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "En complemento de información",
}},
{8, new() {
ssId = 8,
ssLabel = "Canceled",
ssClass = "canceled",
ssOrder = 96,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Cancelado",
}},
{4, new() {
ssId = 4,
ssLabel = "ErrorAPI",
ssClass = "errorAPI",
ssOrder = 95,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Error API",
}},
{7, new() {
ssId = 7,
ssLabel = "Not Paid",
ssClass = "notpaid",
ssOrder = 97,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "No Pagado",
}},
{10, new() {
ssId = 10,
ssLabel = "Pending",
ssClass = "pending",
ssOrder = 99,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = false,
ssIsInv = false,
ssLabelES = "Pendiente",
}},
{2, new() {
ssId = 2,
ssLabel = "Approved",
ssClass = "approved",
ssOrder = 7,
ssIs_Active = true,
ssIsCyA = true,
ssIsCyAApproval = true,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Aprobado",
}},
{9, new() {
ssId = 9,
ssLabel = "Request to Modify",
ssClass = "modify",
ssOrder = 9,
ssIs_Active = true,
ssIsCyA = false,
ssIsCyAApproval = false,
ssIsReq = true,
ssIsInv = true,
ssLabelES = "Por Modificar",
}},
}},

    };
}
}

