using System.Diagnostics;
namespace ssConectaProveedores {

public sealed partial class ENRequisitionEntity {
private static readonly ActivitySource activitySource = new(typeof(ENRequisitionEntity).Namespace);
private static System.Collections.Generic.Dictionary<string,string> _entityAttributes;
private static System.Collections.Generic.Dictionary<string,string> EntityAttributes => _entityAttributes ??= InitializeEntityAttributes();

private static System.Collections.Generic.Dictionary<string,string> InitializeEntityAttributes() {
return new System.Collections.Generic.Dictionary<string,string> {
{"id", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@Id, "id") ?? "id"},
{"name", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@Name, "name") ?? "name"},
{"counter", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@Counter, "counter") ?? "counter"},
{"requisitionstatusid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@RequisitionStatusId, "requisitionstatusid") ?? "requisitionstatusid"},
{"supplierid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@SupplierId, "supplierid") ?? "supplierid"},
{"regionid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@RegionId, "regionid") ?? "regionid"},
{"accountingregionid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@AccountingRegionId, "accountingregionid") ?? "accountingregionid"},
{"applicantid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@ApplicantId, "applicantid") ?? "applicantid"},
{"maxdatefinishcapture", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@MaxDateFinishCapture, "maxdatefinishcapture") ?? "maxdatefinishcapture"},
{"projectassetserviceid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@ProjectAssetServiceId, "projectassetserviceid") ?? "projectassetserviceid"},
{"projectassetservice", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@ProjectAssetService, "projectassetservice") ?? "projectassetservice"},
{"projectdescription", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@ProjectDescription, "projectdescription") ?? "projectdescription"},
{"frequencyid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@FrequencyId, "frequencyid") ?? "frequencyid"},
{"issustainability", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@IsSustainability, "issustainability") ?? "issustainability"},
{"sustainabilityid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@SustainabilityId, "sustainabilityid") ?? "sustainabilityid"},
{"businessvaluecategoryid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@BusinessValueCategoryId, "businessvaluecategoryid") ?? "businessvaluecategoryid"},
{"businessvaluesubcategoryid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@BusinessValueSubcategoryId, "businessvaluesubcategoryid") ?? "businessvaluesubcategoryid"},
{"totalamount", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@TotalAmount, "totalamount") ?? "totalamount"},
{"currencyid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@CurrencyId, "currencyid") ?? "currencyid"},
{"distributionid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@DistributionId, "distributionid") ?? "distributionid"},
{"costcenterid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@CostCenterId, "costcenterid") ?? "costcenterid"},
{"hascontract", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@HasContract, "hascontract") ?? "hascontract"},
{"iscontractpending", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@IsContractPending, "iscontractpending") ?? "iscontractpending"},
{"hasdeposit", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@HasDeposit, "hasdeposit") ?? "hasdeposit"},
{"hasinsurance", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@HasInsurance, "hasinsurance") ?? "hasinsurance"},
{"hasadvancepayment", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@HasAdvancePayment, "hasadvancepayment") ?? "hasadvancepayment"},
{"accountingservicetypeid_depr", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@AccountingServiceTypeId_DEPR, "accountingservicetypeid_depr") ?? "accountingservicetypeid_depr"},
{"servicedescription_deprec", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@ServiceDescription_DEPREC, "servicedescription_deprec") ?? "servicedescription_deprec"},
{"invoiceusageid_deprec", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@InvoiceUsageId_DEPREC, "invoiceusageid_deprec") ?? "invoiceusageid_deprec"},
{"serviceformatid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@ServiceFormatId, "serviceformatid") ?? "serviceformatid"},
{"companyid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@CompanyId, "companyid") ?? "companyid"},
{"retentionrate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@RetentionRate, "retentionrate") ?? "retentionrate"},
{"negotiatedexchangerate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@NegotiatedExchangeRate, "negotiatedexchangerate") ?? "negotiatedexchangerate"},
{"paymentmethodid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@PaymentMethodId, "paymentmethodid") ?? "paymentmethodid"},
{"paymenttermsid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@PaymentTermsId, "paymenttermsid") ?? "paymenttermsid"},
{"isautomaticaccounting", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@IsAutomaticAccounting, "isautomaticaccounting") ?? "isautomaticaccounting"},
{"createdby", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@CreatedBy, "createdby") ?? "createdby"},
{"createdon", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@CreatedOn, "createdon") ?? "createdon"},
{"updatedon", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@UpdatedOn, "updatedon") ?? "updatedon"},
{"updatedby", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@UpdatedBy, "updatedby") ?? "updatedby"},
{"createdbyapplicationrole", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@CreatedByApplicationRole, "createdbyapplicationrole") ?? "createdbyapplicationrole"},
{"dateofcommitment", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@DateOfCommitment, "dateofcommitment") ?? "dateofcommitment"},
{"hascontractfileuploaded", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@HasContractFileUploaded, "hascontractfileuploaded") ?? "hascontractfileuploaded"},
{"hasupdateddateofcommitment", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@HasUpdatedDateOfCommitment, "hasupdateddateofcommitment") ?? "hasupdateddateofcommitment"},
{"submittedon", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@SubmittedOn, "submittedon") ?? "submittedon"},
{"isdonation", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@IsDonation, "isdonation") ?? "isdonation"},
{"advwithoutinvoice", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@AdvWithoutInvoice, "advwithoutinvoice") ?? "advwithoutinvoice"},
{"wasadvwithoutinvoice", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@WasAdvWithoutInvoice, "wasadvwithoutinvoice") ?? "wasadvwithoutinvoice"},
{"isadvanced", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@IsAdvanced, "isadvanced") ?? "isadvanced"},
{"documenttypeid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@DocumentTypeId, "documenttypeid") ?? "documenttypeid"},
{"iscreatedbyanassistente", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@IsCreatedByAnAssistente, "iscreatedbyanassistente") ?? "iscreatedbyanassistente"},
{"telceldirectionid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@TelcelDirectionId, "telceldirectionid") ?? "telceldirectionid"},
{"hasmultiupload", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@HasMultiUpload, "hasmultiupload") ?? "hasmultiupload"},
{"accountingdate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@AccountingDate, "accountingdate") ?? "accountingdate"},
{"paymentoptionsid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@PaymentOptionsId, "paymentoptionsid") ?? "paymentoptionsid"},
{"paymentwaysid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@PaymentWaysId, "paymentwaysid") ?? "paymentwaysid"},
{"buydocnumber", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@BuyDocNumber, "buydocnumber") ?? "buydocnumber"},
{"buydocposition", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, _EntityKeyConstants._ConectaProveedoresEntityKeys._RequisitionAttributeKeys.@BuyDocPosition, "buydocposition") ?? "buydocposition"}
};
}
public static System.Collections.Generic.Dictionary<string,string> AttributesToDatabaseNamesMap() {
return EntityAttributes;
}
public static string AttributeDatabaseName(string attributeName) {
string databaseName;
EntityAttributes.TryGetValue(attributeName, out databaseName);
return databaseName;
}
public static string LocalViewName(string locale) {
return ViewName(locale);
}
public static string ViewName(string locale) {
return BaseAppUtils.EscapeAndQualifySqlIdentifier(DatabaseAccess.ForRuntimeDatabase, TableDetailsServiceAccessor.Instance?.GetValidatedTableName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@Requisition, "requi_u8aqr95gpferhlaxnk9etq23"));
}
} // ENRequisitionEntity

}

