using System.Diagnostics;
namespace ssConectaProveedores {

public sealed partial class ENOrderMainItemEntity {
private static readonly ActivitySource activitySource = new(typeof(ENOrderMainItemEntity).Namespace);
private static System.Collections.Generic.Dictionary<string,string> _entityAttributes;
private static System.Collections.Generic.Dictionary<string,string> EntityAttributes => _entityAttributes ??= InitializeEntityAttributes();

private static System.Collections.Generic.Dictionary<string,string> InitializeEntityAttributes() {
return new System.Collections.Generic.Dictionary<string,string> {
{"id", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@Id, "id") ?? "id"},
{"ordermainid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@OrderMainId, "ordermainid") ?? "ordermainid"},
{"position", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@Position, "position") ?? "position"},
{"materialcode", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@MaterialCode, "materialcode") ?? "materialcode"},
{"materialdescription", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@MaterialDescription, "materialdescription") ?? "materialdescription"},
{"assigmnentcode", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@AssigmnentCode, "assigmnentcode") ?? "assigmnentcode"},
{"documentclassid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@DocumentClassId, "documentclassid") ?? "documentclassid"},
{"deliverydate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@DeliveryDate, "deliverydate") ?? "deliverydate"},
{"quantity", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@Quantity, "quantity") ?? "quantity"},
{"unittype", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@UnitType, "unittype") ?? "unittype"},
{"unitprice", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@UnitPrice, "unitprice") ?? "unitprice"},
{"basequantity", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@BaseQuantity, "basequantity") ?? "basequantity"},
{"isdeleted", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@IsDeleted, "isdeleted") ?? "isdeleted"},
{"isblocked", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@IsBlocked, "isblocked") ?? "isblocked"},
{"isfinaldelivery", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@IsFinalDelivery, "isfinaldelivery") ?? "isfinaldelivery"},
{"glaccountid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@GLAccountId, "glaccountid") ?? "glaccountid"},
{"costcenterid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@CostCenterId, "costcenterid") ?? "costcenterid"},
{"fundscenter", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@FundsCenter, "fundscenter") ?? "fundscenter"},
{"fund", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@Fund, "fund") ?? "fund"},
{"commitmentitem", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@CommitmentItem, "commitmentitem") ?? "commitmentitem"},
{"vatindicator", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@VATIndicator, "vatindicator") ?? "vatindicator"},
{"vatprocedure", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@VATProcedure, "vatprocedure") ?? "vatprocedure"},
{"vatrate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@VATRate, "vatrate") ?? "vatrate"},
{"purchaserequisitionnumber", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@PurchaseRequisitionNumber, "purchaserequisitionnumber") ?? "purchaserequisitionnumber"},
{"purchaserequisitionitemnr", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@PurchaseRequisitionItemNr, "purchaserequisitionitemnr") ?? "purchaserequisitionitemnr"},
{"regionid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@RegionId, "regionid") ?? "regionid"},
{"center", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@Center, "center") ?? "center"},
{"pepelement", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@PEPElement, "pepelement") ?? "pepelement"},
{"quantitydelivered", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@QuantityDelivered, "quantitydelivered") ?? "quantitydelivered"},
{"orderunitofmeasure", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@OrderUnitOfMeasure, "orderunitofmeasure") ?? "orderunitofmeasure"},
{"applicant", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@Applicant, "applicant") ?? "applicant"},
{"direction", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@Direction, "direction") ?? "direction"},
{"contractnumber", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@ContractNumber, "contractnumber") ?? "contractnumber"},
{"contractposition", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@ContractPosition, "contractposition") ?? "contractposition"},
{"contractstartdate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@ContractStartDate, "contractstartdate") ?? "contractstartdate"},
{"contractenddate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@ContractEndDate, "contractenddate") ?? "contractenddate"},
{"contractplannedvalue", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@ContractPlannedValue, "contractplannedvalue") ?? "contractplannedvalue"},
{"positiontype", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@PositionType, "positiontype") ?? "positiontype"},
{"serialnumberprofile", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@SerialNumberProfile, "serialnumberprofile") ?? "serialnumberprofile"},
{"batchmanaged", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@BatchManaged, "batchmanaged") ?? "batchmanaged"},
{"materialtype", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@MaterialType, "materialtype") ?? "materialtype"},
{"itemgroup", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@ItemGroup, "itemgroup") ?? "itemgroup"},
{"orderrequestcreatorsapnumber", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@OrderRequestCreatorSAPNumber, "orderrequestcreatorsapnumber") ?? "orderrequestcreatorsapnumber"},
{"ismultipleimputation", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@IsMultipleImputation, "ismultipleimputation") ?? "ismultipleimputation"},
{"invoiceusageid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@InvoiceUsageId, "invoiceusageid") ?? "invoiceusageid"},
{"ordermainitemstatusid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@OrderMainItemStatusId, "ordermainitemstatusid") ?? "ordermainitemstatusid"},
{"divisionid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@DivisionId, "divisionid") ?? "divisionid"},
{"createdby", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@CreatedBy, "createdby") ?? "createdby"},
{"createdon", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@CreatedOn, "createdon") ?? "createdon"},
{"updatedby", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@UpdatedBy, "updatedby") ?? "updatedby"},
{"updatedon", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderMainItemAttributeKeys.@UpdatedOn, "updatedon") ?? "updatedon"}
};
}
public static System.Collections.Generic.Dictionary<string,string> AttributesToDatabaseNamesMap() {
return EntityAttributes;
}
public static string AttributeDatabaseName(string attributeName) {
string databaseName;
EntityAttributes.TryGetValue(attributeName, out databaseName);
return databaseName;
}
public static string LocalViewName(string locale) {
return ViewName(locale);
}
public static string ViewName(string locale) {
return BaseAppUtils.EscapeAndQualifySqlIdentifier(DatabaseAccess.ForRuntimeDatabase, TableDetailsServiceAccessor.Instance?.GetValidatedTableName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderMainItem, "order_u8aqr95gpfepwm2srz3tce26"));
}
} // ENOrderMainItemEntity

}

