using System.Diagnostics;
namespace ssConectaProveedores {

public sealed partial class ENOrderDetailEntity {
private static readonly ActivitySource activitySource = new(typeof(ENOrderDetailEntity).Namespace);
private static System.Collections.Generic.Dictionary<string,string> _entityAttributes;
private static System.Collections.Generic.Dictionary<string,string> EntityAttributes => _entityAttributes ??= InitializeEntityAttributes();

private static System.Collections.Generic.Dictionary<string,string> InitializeEntityAttributes() {
return new System.Collections.Generic.Dictionary<string,string> {
{"orderid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@OrderId, "orderid") ?? "orderid"},
{"isapprovalfromuserarea", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@IsApprovalFromUserArea, "isapprovalfromuserarea") ?? "isapprovalfromuserarea"},
{"projectassetserviceid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@ProjectAssetServiceId, "projectassetserviceid") ?? "projectassetserviceid"},
{"projectassetservice", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@ProjectAssetService, "projectassetservice") ?? "projectassetservice"},
{"projectdescription", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@ProjectDescription, "projectdescription") ?? "projectdescription"},
{"businessvaluecategoryid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@BusinessValueCategoryId, "businessvaluecategoryid") ?? "businessvaluecategoryid"},
{"businessvaluesubcategoryid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@BusinessValueSubcategoryId, "businessvaluesubcategoryid") ?? "businessvaluesubcategoryid"},
{"paymenttermsid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@PaymentTermsId, "paymenttermsid") ?? "paymenttermsid"},
{"paymentmethodid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@PaymentMethodId, "paymentmethodid") ?? "paymentmethodid"},
{"negotiatedexchangerate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@NegotiatedExchangeRate, "negotiatedexchangerate") ?? "negotiatedexchangerate"},
{"contractstatus", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@ContractStatus, "contractstatus") ?? "contractstatus"},
{"dateofcommitment", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@DateOfCommitment, "dateofcommitment") ?? "dateofcommitment"},
{"hasdeposit", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@HasDeposit, "hasdeposit") ?? "hasdeposit"},
{"hasinsurance", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@HasInsurance, "hasinsurance") ?? "hasinsurance"},
{"distributionid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@DistributionId, "distributionid") ?? "distributionid"},
{"hasadvancepayment", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@HasAdvancePayment, "hasadvancepayment") ?? "hasadvancepayment"},
{"retentionrate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@RetentionRate, "retentionrate") ?? "retentionrate"},
{"hasbasedate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@HasBaseDate, "hasbasedate") ?? "hasbasedate"},
{"startbasedate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@StartBaseDate, "startbasedate") ?? "startbasedate"},
{"endbasedate", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@EndBaseDate, "endbasedate") ?? "endbasedate"},
{"contractnumber", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@ContractNumber, "contractnumber") ?? "contractnumber"},
{"isretentionapplied", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@IsRetentionApplied, "isretentionapplied") ?? "isretentionapplied"},
{"frequency", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@Frequency, "frequency") ?? "frequency"},
{"period", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@Period, "period") ?? "period"},
{"orderretentiontypeid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@OrderRetentionTypeId, "orderretentiontypeid") ?? "orderretentiontypeid"},
{"paymentoptionsid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@PaymentOptionsId, "paymentoptionsid") ?? "paymentoptionsid"},
{"paymentwaysid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@PaymentWaysId, "paymentwaysid") ?? "paymentwaysid"},
{"orderscontract", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@OrdersContract, "orderscontract") ?? "orderscontract"},
{"contractamount", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@ContractAmount, "contractamount") ?? "contractamount"},
{"contracttarif", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@ContractTarif, "contracttarif") ?? "contracttarif"},
{"contractsupplier", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@ContractSupplier, "contractsupplier") ?? "contractsupplier"},
{"isdependentfromfolios", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@IsDependentFromFolios, "isdependentfromfolios") ?? "isdependentfromfolios"},
{"specialapprovalid", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@SpecialApprovalId, "specialapprovalid") ?? "specialapprovalid"},
{"createdby", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@CreatedBy, "createdby") ?? "createdby"},
{"createdon", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@CreatedOn, "createdon") ?? "createdon"},
{"updatedby", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@UpdatedBy, "updatedby") ?? "updatedby"},
{"updatedon", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@UpdatedOn, "updatedon") ?? "updatedon"},
{"allcontactfilesvalidated", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@AllContactFilesValidated, "allcontactfilesvalidated") ?? "allcontactfilesvalidated"},
{"hasntrequestdocuments", TableDetailsServiceAccessor.Instance?.GetValidatedColumnName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, _EntityKeyConstants._ConectaProveedoresEntityKeys._OrderDetailAttributeKeys.@HasntRequestDocuments, "hasntrequestdocuments") ?? "hasntrequestdocuments"}
};
}
public static System.Collections.Generic.Dictionary<string,string> AttributesToDatabaseNamesMap() {
return EntityAttributes;
}
public static string AttributeDatabaseName(string attributeName) {
string databaseName;
EntityAttributes.TryGetValue(attributeName, out databaseName);
return databaseName;
}
public static string LocalViewName(string locale) {
return ViewName(locale);
}
public static string ViewName(string locale) {
return BaseAppUtils.EscapeAndQualifySqlIdentifier(DatabaseAccess.ForRuntimeDatabase, TableDetailsServiceAccessor.Instance?.GetValidatedTableName(_EntityKeyConstants.@ConectaProveedores, _EntityKeyConstants._ConectaProveedoresEntityKeys.@OrderDetail, "order_u8aqr95gpfeu_276zim3tai7"));
}
} // ENOrderDetailEntity

}

